// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package tc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IngressClient is the client API for Ingress service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IngressClient interface {
	// Create a new Ingress
	CreateIngress(ctx context.Context, in *CreateIngressRequest, opts ...grpc.CallOption) (*IngressInfo, error)
	// Update an existing Ingress. Ingress can only be updated when it's in ENDPOINT_WAITING state.
	UpdateIngress(ctx context.Context, in *UpdateIngressRequest, opts ...grpc.CallOption) (*IngressInfo, error)
	ListIngress(ctx context.Context, in *ListIngressRequest, opts ...grpc.CallOption) (*ListIngressResponse, error)
	DeleteIngress(ctx context.Context, in *DeleteIngressRequest, opts ...grpc.CallOption) (*IngressInfo, error)
}

type ingressClient struct {
	cc grpc.ClientConnInterface
}

func NewIngressClient(cc grpc.ClientConnInterface) IngressClient {
	return &ingressClient{cc}
}

func (c *ingressClient) CreateIngress(ctx context.Context, in *CreateIngressRequest, opts ...grpc.CallOption) (*IngressInfo, error) {
	out := new(IngressInfo)
	err := c.cc.Invoke(ctx, "/tc.Ingress/CreateIngress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) UpdateIngress(ctx context.Context, in *UpdateIngressRequest, opts ...grpc.CallOption) (*IngressInfo, error) {
	out := new(IngressInfo)
	err := c.cc.Invoke(ctx, "/tc.Ingress/UpdateIngress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) ListIngress(ctx context.Context, in *ListIngressRequest, opts ...grpc.CallOption) (*ListIngressResponse, error) {
	out := new(ListIngressResponse)
	err := c.cc.Invoke(ctx, "/tc.Ingress/ListIngress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ingressClient) DeleteIngress(ctx context.Context, in *DeleteIngressRequest, opts ...grpc.CallOption) (*IngressInfo, error) {
	out := new(IngressInfo)
	err := c.cc.Invoke(ctx, "/tc.Ingress/DeleteIngress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IngressServer is the server API for Ingress service.
// All implementations must embed UnimplementedIngressServer
// for forward compatibility
type IngressServer interface {
	// Create a new Ingress
	CreateIngress(context.Context, *CreateIngressRequest) (*IngressInfo, error)
	// Update an existing Ingress. Ingress can only be updated when it's in ENDPOINT_WAITING state.
	UpdateIngress(context.Context, *UpdateIngressRequest) (*IngressInfo, error)
	ListIngress(context.Context, *ListIngressRequest) (*ListIngressResponse, error)
	DeleteIngress(context.Context, *DeleteIngressRequest) (*IngressInfo, error)
	mustEmbedUnimplementedIngressServer()
}

// UnimplementedIngressServer must be embedded to have forward compatible implementations.
type UnimplementedIngressServer struct {
}

func (UnimplementedIngressServer) CreateIngress(context.Context, *CreateIngressRequest) (*IngressInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIngress not implemented")
}
func (UnimplementedIngressServer) UpdateIngress(context.Context, *UpdateIngressRequest) (*IngressInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateIngress not implemented")
}
func (UnimplementedIngressServer) ListIngress(context.Context, *ListIngressRequest) (*ListIngressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIngress not implemented")
}
func (UnimplementedIngressServer) DeleteIngress(context.Context, *DeleteIngressRequest) (*IngressInfo, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteIngress not implemented")
}
func (UnimplementedIngressServer) mustEmbedUnimplementedIngressServer() {}

// UnsafeIngressServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IngressServer will
// result in compilation errors.
type UnsafeIngressServer interface {
	mustEmbedUnimplementedIngressServer()
}

func RegisterIngressServer(s grpc.ServiceRegistrar, srv IngressServer) {
	s.RegisterService(&Ingress_ServiceDesc, srv)
}

func _Ingress_CreateIngress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIngressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).CreateIngress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tc.Ingress/CreateIngress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).CreateIngress(ctx, req.(*CreateIngressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_UpdateIngress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateIngressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).UpdateIngress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tc.Ingress/UpdateIngress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).UpdateIngress(ctx, req.(*UpdateIngressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_ListIngress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIngressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).ListIngress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tc.Ingress/ListIngress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).ListIngress(ctx, req.(*ListIngressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Ingress_DeleteIngress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteIngressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IngressServer).DeleteIngress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tc.Ingress/DeleteIngress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IngressServer).DeleteIngress(ctx, req.(*DeleteIngressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Ingress_ServiceDesc is the grpc.ServiceDesc for Ingress service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Ingress_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tc.Ingress",
	HandlerType: (*IngressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIngress",
			Handler:    _Ingress_CreateIngress_Handler,
		},
		{
			MethodName: "UpdateIngress",
			Handler:    _Ingress_UpdateIngress_Handler,
		},
		{
			MethodName: "ListIngress",
			Handler:    _Ingress_ListIngress_Handler,
		},
		{
			MethodName: "DeleteIngress",
			Handler:    _Ingress_DeleteIngress_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tc_ingress.proto",
}
