// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tc_ingress.proto

package tc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type IngressInput int32

const (
	IngressInput_RTMP_INPUT IngressInput = 0
	IngressInput_WHIP_INPUT IngressInput = 1
	IngressInput_URL_INPUT  IngressInput = 2
)

var IngressInput_name = map[int32]string{
	0: "RTMP_INPUT",
	1: "WHIP_INPUT",
	2: "URL_INPUT",
}

var IngressInput_value = map[string]int32{
	"RTMP_INPUT": 0,
	"WHIP_INPUT": 1,
	"URL_INPUT":  2,
}

func (x IngressInput) String() string {
	return proto.EnumName(IngressInput_name, int32(x))
}

func (IngressInput) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{0}
}

type IngressAudioEncodingPreset int32

const (
	IngressAudioEncodingPreset_OPUS_STEREO_96KBPS IngressAudioEncodingPreset = 0
	IngressAudioEncodingPreset_OPUS_MONO_64KBS    IngressAudioEncodingPreset = 1
)

var IngressAudioEncodingPreset_name = map[int32]string{
	0: "OPUS_STEREO_96KBPS",
	1: "OPUS_MONO_64KBS",
}

var IngressAudioEncodingPreset_value = map[string]int32{
	"OPUS_STEREO_96KBPS": 0,
	"OPUS_MONO_64KBS":    1,
}

func (x IngressAudioEncodingPreset) String() string {
	return proto.EnumName(IngressAudioEncodingPreset_name, int32(x))
}

func (IngressAudioEncodingPreset) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{1}
}

type IngressVideoEncodingPreset int32

const (
	IngressVideoEncodingPreset_H264_720P_30FPS_3_LAYERS              IngressVideoEncodingPreset = 0
	IngressVideoEncodingPreset_H264_1080P_30FPS_3_LAYERS             IngressVideoEncodingPreset = 1
	IngressVideoEncodingPreset_H264_540P_25FPS_2_LAYERS              IngressVideoEncodingPreset = 2
	IngressVideoEncodingPreset_H264_720P_30FPS_1_LAYER               IngressVideoEncodingPreset = 3
	IngressVideoEncodingPreset_H264_1080P_30FPS_1_LAYER              IngressVideoEncodingPreset = 4
	IngressVideoEncodingPreset_H264_720P_30FPS_3_LAYERS_HIGH_MOTION  IngressVideoEncodingPreset = 5
	IngressVideoEncodingPreset_H264_1080P_30FPS_3_LAYERS_HIGH_MOTION IngressVideoEncodingPreset = 6
	IngressVideoEncodingPreset_H264_540P_25FPS_2_LAYERS_HIGH_MOTION  IngressVideoEncodingPreset = 7
	IngressVideoEncodingPreset_H264_720P_30FPS_1_LAYER_HIGH_MOTION   IngressVideoEncodingPreset = 8
	IngressVideoEncodingPreset_H264_1080P_30FPS_1_LAYER_HIGH_MOTION  IngressVideoEncodingPreset = 9
)

var IngressVideoEncodingPreset_name = map[int32]string{
	0: "H264_720P_30FPS_3_LAYERS",
	1: "H264_1080P_30FPS_3_LAYERS",
	2: "H264_540P_25FPS_2_LAYERS",
	3: "H264_720P_30FPS_1_LAYER",
	4: "H264_1080P_30FPS_1_LAYER",
	5: "H264_720P_30FPS_3_LAYERS_HIGH_MOTION",
	6: "H264_1080P_30FPS_3_LAYERS_HIGH_MOTION",
	7: "H264_540P_25FPS_2_LAYERS_HIGH_MOTION",
	8: "H264_720P_30FPS_1_LAYER_HIGH_MOTION",
	9: "H264_1080P_30FPS_1_LAYER_HIGH_MOTION",
}

var IngressVideoEncodingPreset_value = map[string]int32{
	"H264_720P_30FPS_3_LAYERS":              0,
	"H264_1080P_30FPS_3_LAYERS":             1,
	"H264_540P_25FPS_2_LAYERS":              2,
	"H264_720P_30FPS_1_LAYER":               3,
	"H264_1080P_30FPS_1_LAYER":              4,
	"H264_720P_30FPS_3_LAYERS_HIGH_MOTION":  5,
	"H264_1080P_30FPS_3_LAYERS_HIGH_MOTION": 6,
	"H264_540P_25FPS_2_LAYERS_HIGH_MOTION":  7,
	"H264_720P_30FPS_1_LAYER_HIGH_MOTION":   8,
	"H264_1080P_30FPS_1_LAYER_HIGH_MOTION":  9,
}

func (x IngressVideoEncodingPreset) String() string {
	return proto.EnumName(IngressVideoEncodingPreset_name, int32(x))
}

func (IngressVideoEncodingPreset) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{2}
}

type IngressState_Status int32

const (
	IngressState_ENDPOINT_INACTIVE   IngressState_Status = 0
	IngressState_ENDPOINT_BUFFERING  IngressState_Status = 1
	IngressState_ENDPOINT_PUBLISHING IngressState_Status = 2
	IngressState_ENDPOINT_ERROR      IngressState_Status = 3
	IngressState_ENDPOINT_COMPLETE   IngressState_Status = 4
)

var IngressState_Status_name = map[int32]string{
	0: "ENDPOINT_INACTIVE",
	1: "ENDPOINT_BUFFERING",
	2: "ENDPOINT_PUBLISHING",
	3: "ENDPOINT_ERROR",
	4: "ENDPOINT_COMPLETE",
}

var IngressState_Status_value = map[string]int32{
	"ENDPOINT_INACTIVE":   0,
	"ENDPOINT_BUFFERING":  1,
	"ENDPOINT_PUBLISHING": 2,
	"ENDPOINT_ERROR":      3,
	"ENDPOINT_COMPLETE":   4,
}

func (x IngressState_Status) String() string {
	return proto.EnumName(IngressState_Status_name, int32(x))
}

func (IngressState_Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{6, 0}
}

type CreateIngressRequest struct {
	InputType IngressInput `protobuf:"varint,1,opt,name=input_type,json=inputType,proto3,enum=tc.IngressInput" json:"input_type,omitempty"`
	// Where to pull media from, only for URL input type
	Url string `protobuf:"bytes,9,opt,name=url,proto3" json:"url,omitempty"`
	// User provided identifier for the ingress
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// room to publish to
	RoomName string `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// publish as participant
	ParticipantIdentity string `protobuf:"bytes,4,opt,name=participant_identity,json=participantIdentity,proto3" json:"participant_identity,omitempty"`
	// name of publishing participant (used for display only)
	ParticipantName string `protobuf:"bytes,5,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	// whether to pass through the incoming media without transcoding, only compatible with some input types
	BypassTranscoding    bool                 `protobuf:"varint,8,opt,name=bypass_transcoding,json=bypassTranscoding,proto3" json:"bypass_transcoding,omitempty"`
	Audio                *IngressAudioOptions `protobuf:"bytes,6,opt,name=audio,proto3" json:"audio,omitempty"`
	Video                *IngressVideoOptions `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *CreateIngressRequest) Reset()         { *m = CreateIngressRequest{} }
func (m *CreateIngressRequest) String() string { return proto.CompactTextString(m) }
func (*CreateIngressRequest) ProtoMessage()    {}
func (*CreateIngressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{0}
}

func (m *CreateIngressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateIngressRequest.Unmarshal(m, b)
}
func (m *CreateIngressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateIngressRequest.Marshal(b, m, deterministic)
}
func (m *CreateIngressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateIngressRequest.Merge(m, src)
}
func (m *CreateIngressRequest) XXX_Size() int {
	return xxx_messageInfo_CreateIngressRequest.Size(m)
}
func (m *CreateIngressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateIngressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateIngressRequest proto.InternalMessageInfo

func (m *CreateIngressRequest) GetInputType() IngressInput {
	if m != nil {
		return m.InputType
	}
	return IngressInput_RTMP_INPUT
}

func (m *CreateIngressRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *CreateIngressRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateIngressRequest) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *CreateIngressRequest) GetParticipantIdentity() string {
	if m != nil {
		return m.ParticipantIdentity
	}
	return ""
}

func (m *CreateIngressRequest) GetParticipantName() string {
	if m != nil {
		return m.ParticipantName
	}
	return ""
}

func (m *CreateIngressRequest) GetBypassTranscoding() bool {
	if m != nil {
		return m.BypassTranscoding
	}
	return false
}

func (m *CreateIngressRequest) GetAudio() *IngressAudioOptions {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *CreateIngressRequest) GetVideo() *IngressVideoOptions {
	if m != nil {
		return m.Video
	}
	return nil
}

type IngressAudioOptions struct {
	Name   string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source TrackSource `protobuf:"varint,2,opt,name=source,proto3,enum=tc.TrackSource" json:"source,omitempty"`
	// Types that are valid to be assigned to EncodingOptions:
	//	*IngressAudioOptions_Preset
	//	*IngressAudioOptions_Options
	EncodingOptions      isIngressAudioOptions_EncodingOptions `protobuf_oneof:"encoding_options"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *IngressAudioOptions) Reset()         { *m = IngressAudioOptions{} }
func (m *IngressAudioOptions) String() string { return proto.CompactTextString(m) }
func (*IngressAudioOptions) ProtoMessage()    {}
func (*IngressAudioOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{1}
}

func (m *IngressAudioOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngressAudioOptions.Unmarshal(m, b)
}
func (m *IngressAudioOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngressAudioOptions.Marshal(b, m, deterministic)
}
func (m *IngressAudioOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngressAudioOptions.Merge(m, src)
}
func (m *IngressAudioOptions) XXX_Size() int {
	return xxx_messageInfo_IngressAudioOptions.Size(m)
}
func (m *IngressAudioOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_IngressAudioOptions.DiscardUnknown(m)
}

var xxx_messageInfo_IngressAudioOptions proto.InternalMessageInfo

func (m *IngressAudioOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IngressAudioOptions) GetSource() TrackSource {
	if m != nil {
		return m.Source
	}
	return TrackSource_UNKNOWN
}

type isIngressAudioOptions_EncodingOptions interface {
	isIngressAudioOptions_EncodingOptions()
}

type IngressAudioOptions_Preset struct {
	Preset IngressAudioEncodingPreset `protobuf:"varint,3,opt,name=preset,proto3,enum=tc.IngressAudioEncodingPreset,oneof"`
}

type IngressAudioOptions_Options struct {
	Options *IngressAudioEncodingOptions `protobuf:"bytes,4,opt,name=options,proto3,oneof"`
}

func (*IngressAudioOptions_Preset) isIngressAudioOptions_EncodingOptions() {}

func (*IngressAudioOptions_Options) isIngressAudioOptions_EncodingOptions() {}

func (m *IngressAudioOptions) GetEncodingOptions() isIngressAudioOptions_EncodingOptions {
	if m != nil {
		return m.EncodingOptions
	}
	return nil
}

func (m *IngressAudioOptions) GetPreset() IngressAudioEncodingPreset {
	if x, ok := m.GetEncodingOptions().(*IngressAudioOptions_Preset); ok {
		return x.Preset
	}
	return IngressAudioEncodingPreset_OPUS_STEREO_96KBPS
}

func (m *IngressAudioOptions) GetOptions() *IngressAudioEncodingOptions {
	if x, ok := m.GetEncodingOptions().(*IngressAudioOptions_Options); ok {
		return x.Options
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IngressAudioOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IngressAudioOptions_Preset)(nil),
		(*IngressAudioOptions_Options)(nil),
	}
}

type IngressVideoOptions struct {
	Name   string      `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Source TrackSource `protobuf:"varint,2,opt,name=source,proto3,enum=tc.TrackSource" json:"source,omitempty"`
	// Types that are valid to be assigned to EncodingOptions:
	//	*IngressVideoOptions_Preset
	//	*IngressVideoOptions_Options
	EncodingOptions      isIngressVideoOptions_EncodingOptions `protobuf_oneof:"encoding_options"`
	XXX_NoUnkeyedLiteral struct{}                              `json:"-"`
	XXX_unrecognized     []byte                                `json:"-"`
	XXX_sizecache        int32                                 `json:"-"`
}

func (m *IngressVideoOptions) Reset()         { *m = IngressVideoOptions{} }
func (m *IngressVideoOptions) String() string { return proto.CompactTextString(m) }
func (*IngressVideoOptions) ProtoMessage()    {}
func (*IngressVideoOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{2}
}

func (m *IngressVideoOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngressVideoOptions.Unmarshal(m, b)
}
func (m *IngressVideoOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngressVideoOptions.Marshal(b, m, deterministic)
}
func (m *IngressVideoOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngressVideoOptions.Merge(m, src)
}
func (m *IngressVideoOptions) XXX_Size() int {
	return xxx_messageInfo_IngressVideoOptions.Size(m)
}
func (m *IngressVideoOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_IngressVideoOptions.DiscardUnknown(m)
}

var xxx_messageInfo_IngressVideoOptions proto.InternalMessageInfo

func (m *IngressVideoOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IngressVideoOptions) GetSource() TrackSource {
	if m != nil {
		return m.Source
	}
	return TrackSource_UNKNOWN
}

type isIngressVideoOptions_EncodingOptions interface {
	isIngressVideoOptions_EncodingOptions()
}

type IngressVideoOptions_Preset struct {
	Preset IngressVideoEncodingPreset `protobuf:"varint,3,opt,name=preset,proto3,enum=tc.IngressVideoEncodingPreset,oneof"`
}

type IngressVideoOptions_Options struct {
	Options *IngressVideoEncodingOptions `protobuf:"bytes,4,opt,name=options,proto3,oneof"`
}

func (*IngressVideoOptions_Preset) isIngressVideoOptions_EncodingOptions() {}

func (*IngressVideoOptions_Options) isIngressVideoOptions_EncodingOptions() {}

func (m *IngressVideoOptions) GetEncodingOptions() isIngressVideoOptions_EncodingOptions {
	if m != nil {
		return m.EncodingOptions
	}
	return nil
}

func (m *IngressVideoOptions) GetPreset() IngressVideoEncodingPreset {
	if x, ok := m.GetEncodingOptions().(*IngressVideoOptions_Preset); ok {
		return x.Preset
	}
	return IngressVideoEncodingPreset_H264_720P_30FPS_3_LAYERS
}

func (m *IngressVideoOptions) GetOptions() *IngressVideoEncodingOptions {
	if x, ok := m.GetEncodingOptions().(*IngressVideoOptions_Options); ok {
		return x.Options
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*IngressVideoOptions) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*IngressVideoOptions_Preset)(nil),
		(*IngressVideoOptions_Options)(nil),
	}
}

type IngressAudioEncodingOptions struct {
	// desired audio codec to publish to room
	AudioCodec           AudioCodec `protobuf:"varint,1,opt,name=audio_codec,json=audioCodec,proto3,enum=tc.AudioCodec" json:"audio_codec,omitempty"`
	Bitrate              uint32     `protobuf:"varint,2,opt,name=bitrate,proto3" json:"bitrate,omitempty"`
	DisableDtx           bool       `protobuf:"varint,3,opt,name=disable_dtx,json=disableDtx,proto3" json:"disable_dtx,omitempty"`
	Channels             uint32     `protobuf:"varint,4,opt,name=channels,proto3" json:"channels,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *IngressAudioEncodingOptions) Reset()         { *m = IngressAudioEncodingOptions{} }
func (m *IngressAudioEncodingOptions) String() string { return proto.CompactTextString(m) }
func (*IngressAudioEncodingOptions) ProtoMessage()    {}
func (*IngressAudioEncodingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{3}
}

func (m *IngressAudioEncodingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngressAudioEncodingOptions.Unmarshal(m, b)
}
func (m *IngressAudioEncodingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngressAudioEncodingOptions.Marshal(b, m, deterministic)
}
func (m *IngressAudioEncodingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngressAudioEncodingOptions.Merge(m, src)
}
func (m *IngressAudioEncodingOptions) XXX_Size() int {
	return xxx_messageInfo_IngressAudioEncodingOptions.Size(m)
}
func (m *IngressAudioEncodingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_IngressAudioEncodingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_IngressAudioEncodingOptions proto.InternalMessageInfo

func (m *IngressAudioEncodingOptions) GetAudioCodec() AudioCodec {
	if m != nil {
		return m.AudioCodec
	}
	return AudioCodec_DEFAULT_AC
}

func (m *IngressAudioEncodingOptions) GetBitrate() uint32 {
	if m != nil {
		return m.Bitrate
	}
	return 0
}

func (m *IngressAudioEncodingOptions) GetDisableDtx() bool {
	if m != nil {
		return m.DisableDtx
	}
	return false
}

func (m *IngressAudioEncodingOptions) GetChannels() uint32 {
	if m != nil {
		return m.Channels
	}
	return 0
}

type IngressVideoEncodingOptions struct {
	// desired codec to publish to room
	VideoCodec VideoCodec `protobuf:"varint,1,opt,name=video_codec,json=videoCodec,proto3,enum=tc.VideoCodec" json:"video_codec,omitempty"`
	FrameRate  float64    `protobuf:"fixed64,2,opt,name=frame_rate,json=frameRate,proto3" json:"frame_rate,omitempty"`
	// simulcast layers to publish, when empty, should usually be set to layers at 1/2 and 1/4 of the dimensions
	Layers               []*VideoLayer `protobuf:"bytes,3,rep,name=layers,proto3" json:"layers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *IngressVideoEncodingOptions) Reset()         { *m = IngressVideoEncodingOptions{} }
func (m *IngressVideoEncodingOptions) String() string { return proto.CompactTextString(m) }
func (*IngressVideoEncodingOptions) ProtoMessage()    {}
func (*IngressVideoEncodingOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{4}
}

func (m *IngressVideoEncodingOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngressVideoEncodingOptions.Unmarshal(m, b)
}
func (m *IngressVideoEncodingOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngressVideoEncodingOptions.Marshal(b, m, deterministic)
}
func (m *IngressVideoEncodingOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngressVideoEncodingOptions.Merge(m, src)
}
func (m *IngressVideoEncodingOptions) XXX_Size() int {
	return xxx_messageInfo_IngressVideoEncodingOptions.Size(m)
}
func (m *IngressVideoEncodingOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_IngressVideoEncodingOptions.DiscardUnknown(m)
}

var xxx_messageInfo_IngressVideoEncodingOptions proto.InternalMessageInfo

func (m *IngressVideoEncodingOptions) GetVideoCodec() VideoCodec {
	if m != nil {
		return m.VideoCodec
	}
	return VideoCodec_DEFAULT_VC
}

func (m *IngressVideoEncodingOptions) GetFrameRate() float64 {
	if m != nil {
		return m.FrameRate
	}
	return 0
}

func (m *IngressVideoEncodingOptions) GetLayers() []*VideoLayer {
	if m != nil {
		return m.Layers
	}
	return nil
}

type IngressInfo struct {
	IngressId string `protobuf:"bytes,1,opt,name=ingress_id,json=ingressId,proto3" json:"ingress_id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	StreamKey string `protobuf:"bytes,3,opt,name=stream_key,json=streamKey,proto3" json:"stream_key,omitempty"`
	Url       string `protobuf:"bytes,4,opt,name=url,proto3" json:"url,omitempty"`
	// for RTMP input, it'll be a rtmp:// URL
	// for FILE input, it'll be a http:// URL
	// for SRT input, it'll be a srt:// URL
	InputType            IngressInput         `protobuf:"varint,5,opt,name=input_type,json=inputType,proto3,enum=tc.IngressInput" json:"input_type,omitempty"`
	BypassTranscoding    bool                 `protobuf:"varint,13,opt,name=bypass_transcoding,json=bypassTranscoding,proto3" json:"bypass_transcoding,omitempty"`
	Audio                *IngressAudioOptions `protobuf:"bytes,6,opt,name=audio,proto3" json:"audio,omitempty"`
	Video                *IngressVideoOptions `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	RoomName             string               `protobuf:"bytes,8,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	ParticipantIdentity  string               `protobuf:"bytes,9,opt,name=participant_identity,json=participantIdentity,proto3" json:"participant_identity,omitempty"`
	ParticipantName      string               `protobuf:"bytes,10,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	Reusable             bool                 `protobuf:"varint,11,opt,name=reusable,proto3" json:"reusable,omitempty"`
	State                *IngressState        `protobuf:"bytes,12,opt,name=state,proto3" json:"state,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *IngressInfo) Reset()         { *m = IngressInfo{} }
func (m *IngressInfo) String() string { return proto.CompactTextString(m) }
func (*IngressInfo) ProtoMessage()    {}
func (*IngressInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{5}
}

func (m *IngressInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngressInfo.Unmarshal(m, b)
}
func (m *IngressInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngressInfo.Marshal(b, m, deterministic)
}
func (m *IngressInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngressInfo.Merge(m, src)
}
func (m *IngressInfo) XXX_Size() int {
	return xxx_messageInfo_IngressInfo.Size(m)
}
func (m *IngressInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_IngressInfo.DiscardUnknown(m)
}

var xxx_messageInfo_IngressInfo proto.InternalMessageInfo

func (m *IngressInfo) GetIngressId() string {
	if m != nil {
		return m.IngressId
	}
	return ""
}

func (m *IngressInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *IngressInfo) GetStreamKey() string {
	if m != nil {
		return m.StreamKey
	}
	return ""
}

func (m *IngressInfo) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *IngressInfo) GetInputType() IngressInput {
	if m != nil {
		return m.InputType
	}
	return IngressInput_RTMP_INPUT
}

func (m *IngressInfo) GetBypassTranscoding() bool {
	if m != nil {
		return m.BypassTranscoding
	}
	return false
}

func (m *IngressInfo) GetAudio() *IngressAudioOptions {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *IngressInfo) GetVideo() *IngressVideoOptions {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *IngressInfo) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *IngressInfo) GetParticipantIdentity() string {
	if m != nil {
		return m.ParticipantIdentity
	}
	return ""
}

func (m *IngressInfo) GetParticipantName() string {
	if m != nil {
		return m.ParticipantName
	}
	return ""
}

func (m *IngressInfo) GetReusable() bool {
	if m != nil {
		return m.Reusable
	}
	return false
}

func (m *IngressInfo) GetState() *IngressState {
	if m != nil {
		return m.State
	}
	return nil
}

type IngressState struct {
	Status               IngressState_Status `protobuf:"varint,1,opt,name=status,proto3,enum=tc.IngressState_Status" json:"status,omitempty"`
	Error                string              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Video                *InputVideoState    `protobuf:"bytes,3,opt,name=video,proto3" json:"video,omitempty"`
	Audio                *InputAudioState    `protobuf:"bytes,4,opt,name=audio,proto3" json:"audio,omitempty"`
	RoomId               string              `protobuf:"bytes,5,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	StartedAt            int64               `protobuf:"varint,7,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt              int64               `protobuf:"varint,8,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	ResourceId           string              `protobuf:"bytes,9,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Tracks               []*TrackInfo        `protobuf:"bytes,6,rep,name=tracks,proto3" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *IngressState) Reset()         { *m = IngressState{} }
func (m *IngressState) String() string { return proto.CompactTextString(m) }
func (*IngressState) ProtoMessage()    {}
func (*IngressState) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{6}
}

func (m *IngressState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IngressState.Unmarshal(m, b)
}
func (m *IngressState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IngressState.Marshal(b, m, deterministic)
}
func (m *IngressState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IngressState.Merge(m, src)
}
func (m *IngressState) XXX_Size() int {
	return xxx_messageInfo_IngressState.Size(m)
}
func (m *IngressState) XXX_DiscardUnknown() {
	xxx_messageInfo_IngressState.DiscardUnknown(m)
}

var xxx_messageInfo_IngressState proto.InternalMessageInfo

func (m *IngressState) GetStatus() IngressState_Status {
	if m != nil {
		return m.Status
	}
	return IngressState_ENDPOINT_INACTIVE
}

func (m *IngressState) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func (m *IngressState) GetVideo() *InputVideoState {
	if m != nil {
		return m.Video
	}
	return nil
}

func (m *IngressState) GetAudio() *InputAudioState {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *IngressState) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *IngressState) GetStartedAt() int64 {
	if m != nil {
		return m.StartedAt
	}
	return 0
}

func (m *IngressState) GetEndedAt() int64 {
	if m != nil {
		return m.EndedAt
	}
	return 0
}

func (m *IngressState) GetResourceId() string {
	if m != nil {
		return m.ResourceId
	}
	return ""
}

func (m *IngressState) GetTracks() []*TrackInfo {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type InputVideoState struct {
	MimeType             string   `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	AverageBitrate       uint32   `protobuf:"varint,2,opt,name=average_bitrate,json=averageBitrate,proto3" json:"average_bitrate,omitempty"`
	Width                uint32   `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	Framerate            float64  `protobuf:"fixed64,5,opt,name=framerate,proto3" json:"framerate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputVideoState) Reset()         { *m = InputVideoState{} }
func (m *InputVideoState) String() string { return proto.CompactTextString(m) }
func (*InputVideoState) ProtoMessage()    {}
func (*InputVideoState) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{7}
}

func (m *InputVideoState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputVideoState.Unmarshal(m, b)
}
func (m *InputVideoState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputVideoState.Marshal(b, m, deterministic)
}
func (m *InputVideoState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputVideoState.Merge(m, src)
}
func (m *InputVideoState) XXX_Size() int {
	return xxx_messageInfo_InputVideoState.Size(m)
}
func (m *InputVideoState) XXX_DiscardUnknown() {
	xxx_messageInfo_InputVideoState.DiscardUnknown(m)
}

var xxx_messageInfo_InputVideoState proto.InternalMessageInfo

func (m *InputVideoState) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *InputVideoState) GetAverageBitrate() uint32 {
	if m != nil {
		return m.AverageBitrate
	}
	return 0
}

func (m *InputVideoState) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *InputVideoState) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *InputVideoState) GetFramerate() float64 {
	if m != nil {
		return m.Framerate
	}
	return 0
}

type InputAudioState struct {
	MimeType             string   `protobuf:"bytes,1,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	AverageBitrate       uint32   `protobuf:"varint,2,opt,name=average_bitrate,json=averageBitrate,proto3" json:"average_bitrate,omitempty"`
	Channels             uint32   `protobuf:"varint,3,opt,name=channels,proto3" json:"channels,omitempty"`
	SampleRate           uint32   `protobuf:"varint,4,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InputAudioState) Reset()         { *m = InputAudioState{} }
func (m *InputAudioState) String() string { return proto.CompactTextString(m) }
func (*InputAudioState) ProtoMessage()    {}
func (*InputAudioState) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{8}
}

func (m *InputAudioState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InputAudioState.Unmarshal(m, b)
}
func (m *InputAudioState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InputAudioState.Marshal(b, m, deterministic)
}
func (m *InputAudioState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InputAudioState.Merge(m, src)
}
func (m *InputAudioState) XXX_Size() int {
	return xxx_messageInfo_InputAudioState.Size(m)
}
func (m *InputAudioState) XXX_DiscardUnknown() {
	xxx_messageInfo_InputAudioState.DiscardUnknown(m)
}

var xxx_messageInfo_InputAudioState proto.InternalMessageInfo

func (m *InputAudioState) GetMimeType() string {
	if m != nil {
		return m.MimeType
	}
	return ""
}

func (m *InputAudioState) GetAverageBitrate() uint32 {
	if m != nil {
		return m.AverageBitrate
	}
	return 0
}

func (m *InputAudioState) GetChannels() uint32 {
	if m != nil {
		return m.Channels
	}
	return 0
}

func (m *InputAudioState) GetSampleRate() uint32 {
	if m != nil {
		return m.SampleRate
	}
	return 0
}

type UpdateIngressRequest struct {
	IngressId            string               `protobuf:"bytes,1,opt,name=ingress_id,json=ingressId,proto3" json:"ingress_id,omitempty"`
	Name                 string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RoomName             string               `protobuf:"bytes,3,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	ParticipantIdentity  string               `protobuf:"bytes,4,opt,name=participant_identity,json=participantIdentity,proto3" json:"participant_identity,omitempty"`
	ParticipantName      string               `protobuf:"bytes,5,opt,name=participant_name,json=participantName,proto3" json:"participant_name,omitempty"`
	BypassTranscoding    bool                 `protobuf:"varint,8,opt,name=bypass_transcoding,json=bypassTranscoding,proto3" json:"bypass_transcoding,omitempty"`
	Audio                *IngressAudioOptions `protobuf:"bytes,6,opt,name=audio,proto3" json:"audio,omitempty"`
	Video                *IngressVideoOptions `protobuf:"bytes,7,opt,name=video,proto3" json:"video,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateIngressRequest) Reset()         { *m = UpdateIngressRequest{} }
func (m *UpdateIngressRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateIngressRequest) ProtoMessage()    {}
func (*UpdateIngressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{9}
}

func (m *UpdateIngressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateIngressRequest.Unmarshal(m, b)
}
func (m *UpdateIngressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateIngressRequest.Marshal(b, m, deterministic)
}
func (m *UpdateIngressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateIngressRequest.Merge(m, src)
}
func (m *UpdateIngressRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateIngressRequest.Size(m)
}
func (m *UpdateIngressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateIngressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateIngressRequest proto.InternalMessageInfo

func (m *UpdateIngressRequest) GetIngressId() string {
	if m != nil {
		return m.IngressId
	}
	return ""
}

func (m *UpdateIngressRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateIngressRequest) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *UpdateIngressRequest) GetParticipantIdentity() string {
	if m != nil {
		return m.ParticipantIdentity
	}
	return ""
}

func (m *UpdateIngressRequest) GetParticipantName() string {
	if m != nil {
		return m.ParticipantName
	}
	return ""
}

func (m *UpdateIngressRequest) GetBypassTranscoding() bool {
	if m != nil {
		return m.BypassTranscoding
	}
	return false
}

func (m *UpdateIngressRequest) GetAudio() *IngressAudioOptions {
	if m != nil {
		return m.Audio
	}
	return nil
}

func (m *UpdateIngressRequest) GetVideo() *IngressVideoOptions {
	if m != nil {
		return m.Video
	}
	return nil
}

type ListIngressRequest struct {
	// when blank, lists all ingress endpoints
	RoomName             string   `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	IngressId            string   `protobuf:"bytes,2,opt,name=ingress_id,json=ingressId,proto3" json:"ingress_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListIngressRequest) Reset()         { *m = ListIngressRequest{} }
func (m *ListIngressRequest) String() string { return proto.CompactTextString(m) }
func (*ListIngressRequest) ProtoMessage()    {}
func (*ListIngressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{10}
}

func (m *ListIngressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIngressRequest.Unmarshal(m, b)
}
func (m *ListIngressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIngressRequest.Marshal(b, m, deterministic)
}
func (m *ListIngressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIngressRequest.Merge(m, src)
}
func (m *ListIngressRequest) XXX_Size() int {
	return xxx_messageInfo_ListIngressRequest.Size(m)
}
func (m *ListIngressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIngressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListIngressRequest proto.InternalMessageInfo

func (m *ListIngressRequest) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *ListIngressRequest) GetIngressId() string {
	if m != nil {
		return m.IngressId
	}
	return ""
}

type ListIngressResponse struct {
	Items                []*IngressInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ListIngressResponse) Reset()         { *m = ListIngressResponse{} }
func (m *ListIngressResponse) String() string { return proto.CompactTextString(m) }
func (*ListIngressResponse) ProtoMessage()    {}
func (*ListIngressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{11}
}

func (m *ListIngressResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListIngressResponse.Unmarshal(m, b)
}
func (m *ListIngressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListIngressResponse.Marshal(b, m, deterministic)
}
func (m *ListIngressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListIngressResponse.Merge(m, src)
}
func (m *ListIngressResponse) XXX_Size() int {
	return xxx_messageInfo_ListIngressResponse.Size(m)
}
func (m *ListIngressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListIngressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListIngressResponse proto.InternalMessageInfo

func (m *ListIngressResponse) GetItems() []*IngressInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteIngressRequest struct {
	IngressId            string   `protobuf:"bytes,1,opt,name=ingress_id,json=ingressId,proto3" json:"ingress_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteIngressRequest) Reset()         { *m = DeleteIngressRequest{} }
func (m *DeleteIngressRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteIngressRequest) ProtoMessage()    {}
func (*DeleteIngressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_455c918368ee0fc3, []int{12}
}

func (m *DeleteIngressRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteIngressRequest.Unmarshal(m, b)
}
func (m *DeleteIngressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteIngressRequest.Marshal(b, m, deterministic)
}
func (m *DeleteIngressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteIngressRequest.Merge(m, src)
}
func (m *DeleteIngressRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteIngressRequest.Size(m)
}
func (m *DeleteIngressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteIngressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteIngressRequest proto.InternalMessageInfo

func (m *DeleteIngressRequest) GetIngressId() string {
	if m != nil {
		return m.IngressId
	}
	return ""
}

func init() {
	proto.RegisterEnum("tc.IngressInput", IngressInput_name, IngressInput_value)
	proto.RegisterEnum("tc.IngressAudioEncodingPreset", IngressAudioEncodingPreset_name, IngressAudioEncodingPreset_value)
	proto.RegisterEnum("tc.IngressVideoEncodingPreset", IngressVideoEncodingPreset_name, IngressVideoEncodingPreset_value)
	proto.RegisterEnum("tc.IngressState_Status", IngressState_Status_name, IngressState_Status_value)
	proto.RegisterType((*CreateIngressRequest)(nil), "tc.CreateIngressRequest")
	proto.RegisterType((*IngressAudioOptions)(nil), "tc.IngressAudioOptions")
	proto.RegisterType((*IngressVideoOptions)(nil), "tc.IngressVideoOptions")
	proto.RegisterType((*IngressAudioEncodingOptions)(nil), "tc.IngressAudioEncodingOptions")
	proto.RegisterType((*IngressVideoEncodingOptions)(nil), "tc.IngressVideoEncodingOptions")
	proto.RegisterType((*IngressInfo)(nil), "tc.IngressInfo")
	proto.RegisterType((*IngressState)(nil), "tc.IngressState")
	proto.RegisterType((*InputVideoState)(nil), "tc.InputVideoState")
	proto.RegisterType((*InputAudioState)(nil), "tc.InputAudioState")
	proto.RegisterType((*UpdateIngressRequest)(nil), "tc.UpdateIngressRequest")
	proto.RegisterType((*ListIngressRequest)(nil), "tc.ListIngressRequest")
	proto.RegisterType((*ListIngressResponse)(nil), "tc.ListIngressResponse")
	proto.RegisterType((*DeleteIngressRequest)(nil), "tc.DeleteIngressRequest")
}

func init() { proto.RegisterFile("tc_ingress.proto", fileDescriptor_455c918368ee0fc3) }

var fileDescriptor_455c918368ee0fc3 = []byte{
	// 1339 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xec, 0x57, 0xdd, 0x72, 0xdb, 0x54,
	0x10, 0x8e, 0xec, 0xf8, 0x6f, 0x5d, 0xdb, 0xea, 0x49, 0x68, 0xdc, 0xb4, 0xa5, 0xc1, 0xa5, 0x6d,
	0xd2, 0x99, 0x26, 0xa9, 0xfb, 0x43, 0x29, 0x3f, 0x33, 0x71, 0xea, 0xd6, 0x9a, 0x26, 0xb6, 0xe7,
	0xd8, 0x29, 0x03, 0x37, 0x67, 0x14, 0xe9, 0x24, 0xd1, 0xd4, 0x96, 0x84, 0x74, 0x1c, 0xea, 0xe1,
	0x96, 0x47, 0x80, 0x27, 0x60, 0x78, 0x12, 0x9e, 0x80, 0x07, 0xe0, 0x15, 0xb8, 0xe3, 0x92, 0x19,
	0xe6, 0xfc, 0x58, 0x91, 0x6c, 0x07, 0xda, 0x0e, 0x0c, 0x37, 0xdc, 0x69, 0xbf, 0x6f, 0xcf, 0x6a,
	0x77, 0xcf, 0xee, 0x67, 0x19, 0x74, 0x66, 0x11, 0xc7, 0x3d, 0x0e, 0x68, 0x18, 0x6e, 0xfa, 0x81,
	0xc7, 0x3c, 0x94, 0x62, 0xd6, 0x6a, 0x85, 0x59, 0x64, 0xe8, 0xd9, 0x74, 0xa0, 0xc0, 0xda, 0xef,
	0x29, 0x58, 0xde, 0x0d, 0xa8, 0xc9, 0xa8, 0x21, 0x9d, 0x31, 0xfd, 0x7a, 0x44, 0x43, 0x86, 0xb6,
	0x00, 0x1c, 0xd7, 0x1f, 0x31, 0xc2, 0xc6, 0x3e, 0xad, 0x6a, 0x6b, 0xda, 0x7a, 0xb9, 0xae, 0x6f,
	0x32, 0x6b, 0x53, 0xf9, 0x19, 0x9c, 0xc4, 0x05, 0xe1, 0xd3, 0x1f, 0xfb, 0x14, 0xe9, 0x90, 0x1e,
	0x05, 0x83, 0x6a, 0x61, 0x4d, 0x5b, 0x2f, 0x60, 0xfe, 0x88, 0x10, 0x2c, 0xba, 0xe6, 0x90, 0x56,
	0x53, 0x02, 0x12, 0xcf, 0xe8, 0x0a, 0x14, 0x02, 0xcf, 0x1b, 0x12, 0x41, 0xa4, 0x05, 0x91, 0xe7,
	0x40, 0x9b, 0x93, 0xf7, 0x60, 0xd9, 0x37, 0x03, 0xe6, 0x58, 0x8e, 0x6f, 0xba, 0x8c, 0x38, 0x36,
	0x75, 0x99, 0xc3, 0xc6, 0xd5, 0x45, 0xe1, 0xb7, 0x14, 0xe3, 0x0c, 0x45, 0xa1, 0x0d, 0xd0, 0xe3,
	0x47, 0x44, 0xd8, 0x8c, 0x70, 0xaf, 0xc4, 0x70, 0x11, 0xfd, 0x2e, 0xa0, 0xc3, 0xb1, 0x6f, 0x86,
	0x21, 0x61, 0x81, 0xe9, 0x86, 0x96, 0x67, 0x3b, 0xee, 0x71, 0x35, 0xbf, 0xa6, 0xad, 0xe7, 0xf1,
	0x45, 0xc9, 0xf4, 0xcf, 0x08, 0x74, 0x17, 0x32, 0xe6, 0xc8, 0x76, 0xbc, 0x6a, 0x76, 0x4d, 0x5b,
	0x2f, 0xd6, 0x57, 0x62, 0xb5, 0xef, 0x70, 0xbc, 0xe3, 0x33, 0xc7, 0x73, 0x43, 0x2c, 0xbd, 0xb8,
	0xfb, 0xa9, 0x63, 0x53, 0xaf, 0x9a, 0x9b, 0x71, 0x7f, 0xc9, 0xf1, 0xc8, 0x5d, 0x78, 0xd5, 0x7e,
	0xd5, 0x60, 0x69, 0x4e, 0xb4, 0xa8, 0x67, 0x5a, 0xac, 0x67, 0xb7, 0x21, 0x1b, 0x7a, 0xa3, 0xc0,
	0x92, 0x9d, 0x2c, 0xd7, 0x2b, 0x3c, 0x76, 0x3f, 0x30, 0xad, 0x57, 0x3d, 0x01, 0x63, 0x45, 0xa3,
	0xc7, 0x90, 0xf5, 0x03, 0x1a, 0x52, 0x26, 0x3a, 0x5b, 0xae, 0xbf, 0x3f, 0x9d, 0x73, 0xd3, 0x95,
	0xc5, 0x75, 0x85, 0x57, 0x6b, 0x01, 0x2b, 0x7f, 0xf4, 0x09, 0xe4, 0x3c, 0x99, 0x81, 0x68, 0x76,
	0xb1, 0x7e, 0xfd, 0xbc, 0xa3, 0x2a, 0xd1, 0xd6, 0x02, 0x9e, 0x9c, 0x68, 0x20, 0xd0, 0xa9, 0x62,
	0x89, 0xc2, 0xe2, 0xf5, 0xc5, 0xcb, 0xff, 0xf7, 0xea, 0x13, 0x6f, 0x79, 0xb7, 0xfa, 0x12, 0x47,
	0xdf, 0xb0, 0xbe, 0x9f, 0x34, 0xb8, 0xf2, 0x17, 0xed, 0x41, 0x5b, 0x50, 0x14, 0x73, 0x41, 0x2c,
	0xcf, 0xa6, 0x96, 0xda, 0x9f, 0x32, 0x7f, 0xa9, 0x70, 0xdf, 0xe5, 0x28, 0x06, 0x33, 0x7a, 0x46,
	0x55, 0xc8, 0x1d, 0x3a, 0x2c, 0x30, 0x99, 0xec, 0x42, 0x09, 0x4f, 0x4c, 0x74, 0x1d, 0x8a, 0xb6,
	0x13, 0x9a, 0x87, 0x03, 0x4a, 0x6c, 0xf6, 0x5a, 0x94, 0x9e, 0xc7, 0xa0, 0xa0, 0xa7, 0xec, 0x35,
	0x5a, 0x85, 0xbc, 0x75, 0x62, 0xba, 0x2e, 0x1d, 0xc8, 0xea, 0x4a, 0x38, 0xb2, 0x6b, 0x3f, 0x9c,
	0xe5, 0x39, 0xaf, 0x4c, 0x9e, 0xa7, 0x18, 0xc8, 0xd9, 0x3c, 0x85, 0xbb, 0xca, 0xf3, 0x34, 0x7a,
	0x46, 0xd7, 0x00, 0x8e, 0x02, 0x73, 0x48, 0x49, 0x94, 0xaa, 0x86, 0x0b, 0x02, 0xc1, 0x3c, 0xd9,
	0x5b, 0x90, 0x1d, 0x98, 0x63, 0x1a, 0x84, 0xd5, 0xf4, 0x5a, 0x7a, 0xbd, 0x18, 0x0b, 0xb5, 0xc7,
	0x61, 0xac, 0xd8, 0xda, 0x6f, 0x69, 0x28, 0x46, 0x4a, 0x72, 0xe4, 0xf1, 0xb0, 0x4a, 0xad, 0x88,
	0x63, 0xab, 0xe9, 0x28, 0x28, 0xc4, 0xb0, 0xe7, 0x4a, 0xc9, 0x35, 0x80, 0x90, 0x05, 0xd4, 0x1c,
	0x92, 0x57, 0x74, 0xac, 0xb4, 0xa4, 0x20, 0x91, 0x17, 0x74, 0x3c, 0xd1, 0xa3, 0xc5, 0x33, 0x3d,
	0x4a, 0x4a, 0x5a, 0xe6, 0xef, 0x25, 0x6d, 0xbe, 0x62, 0x94, 0xfe, 0x13, 0xc5, 0x48, 0x2a, 0x67,
	0xfe, 0x0d, 0x95, 0xb3, 0xf0, 0x76, 0xca, 0x09, 0xf3, 0x95, 0x73, 0x15, 0xf2, 0x01, 0x1d, 0x89,
	0x79, 0xab, 0x16, 0x45, 0xf5, 0x91, 0x8d, 0x6e, 0x41, 0x26, 0x64, 0x7c, 0x14, 0x2e, 0x88, 0x2a,
	0xe2, 0xfd, 0xec, 0x71, 0x1c, 0x4b, 0xba, 0xf6, 0x73, 0x1a, 0x2e, 0xc4, 0x71, 0xb4, 0x05, 0x59,
	0xce, 0x8c, 0x42, 0x35, 0x74, 0x2b, 0xd3, 0x27, 0x37, 0x7b, 0x82, 0xc6, 0xca, 0x0d, 0x2d, 0x43,
	0x86, 0x06, 0x81, 0x17, 0xa8, 0x21, 0x90, 0x06, 0xda, 0x98, 0x74, 0x31, 0x2d, 0xde, 0xbf, 0x24,
	0xa3, 0xf8, 0x23, 0x26, 0x7a, 0xa8, 0x52, 0x90, 0x1d, 0xdc, 0x98, 0xdc, 0xcf, 0xe2, 0x94, 0xab,
	0xb8, 0x1d, 0xe5, 0x2a, 0xef, 0x66, 0x05, 0x72, 0xa2, 0xd9, 0x8e, 0xad, 0x7e, 0x4d, 0xb2, 0xdc,
	0x34, 0x6c, 0x39, 0x74, 0x66, 0xc0, 0xa8, 0x4d, 0x4c, 0x26, 0x6e, 0x2e, 0xcd, 0x87, 0x4e, 0x20,
	0x3b, 0x0c, 0x5d, 0x86, 0x3c, 0x75, 0x6d, 0x49, 0xe6, 0x05, 0x99, 0x13, 0xf6, 0x0e, 0xe3, 0x6b,
	0x1c, 0x50, 0x29, 0x64, 0x3c, 0xac, 0xbc, 0x19, 0x98, 0x40, 0x86, 0x8d, 0x6e, 0x42, 0x96, 0x71,
	0xd1, 0x0b, 0xab, 0x59, 0xb1, 0x3a, 0xa5, 0x48, 0x06, 0xf9, 0x86, 0x60, 0x45, 0xd6, 0xbe, 0x85,
	0xac, 0x6c, 0x0c, 0x7a, 0x0f, 0x2e, 0x36, 0xdb, 0x4f, 0xbb, 0x1d, 0xa3, 0xdd, 0x27, 0x46, 0x7b,
	0x67, 0xb7, 0x6f, 0xbc, 0x6c, 0xea, 0x0b, 0xe8, 0x12, 0xa0, 0x08, 0x6e, 0x1c, 0x3c, 0x7b, 0xd6,
	0xc4, 0x46, 0xfb, 0xb9, 0xae, 0xa1, 0x15, 0x58, 0x8a, 0xf0, 0xee, 0x41, 0x63, 0xcf, 0xe8, 0xb5,
	0x38, 0x91, 0x42, 0x08, 0xca, 0x11, 0xd1, 0xc4, 0xb8, 0x83, 0xf5, 0x74, 0x22, 0xf6, 0x6e, 0x67,
	0xbf, 0xbb, 0xd7, 0xec, 0x37, 0xf5, 0xc5, 0xda, 0x8f, 0x1a, 0x54, 0xa6, 0xba, 0xcb, 0x07, 0x73,
	0xe8, 0x0c, 0xe9, 0xd9, 0x87, 0x42, 0x01, 0xe7, 0x39, 0x20, 0x56, 0xe8, 0x36, 0x54, 0xcc, 0x53,
	0x1a, 0x98, 0xc7, 0x94, 0x24, 0xe5, 0xad, 0xac, 0xe0, 0x86, 0x52, 0xb9, 0x65, 0xc8, 0x7c, 0xe3,
	0xd8, 0xec, 0x44, 0xdc, 0x63, 0x09, 0x4b, 0x03, 0x5d, 0x82, 0xec, 0x09, 0x75, 0x8e, 0x4f, 0x98,
	0x12, 0x36, 0x65, 0xa1, 0xab, 0x20, 0x35, 0x47, 0x04, 0xcc, 0xc4, 0x44, 0x88, 0x03, 0xb5, 0xef,
	0x27, 0x59, 0x9e, 0x5d, 0xec, 0x3f, 0x94, 0x65, 0x5c, 0x6a, 0xd3, 0x49, 0xa9, 0xe5, 0x17, 0x1c,
	0x9a, 0x43, 0x7f, 0xa0, 0xa4, 0x51, 0x26, 0x0c, 0x12, 0xe2, 0xda, 0x58, 0xfb, 0x25, 0x05, 0xcb,
	0x07, 0xbe, 0x3d, 0xfb, 0xad, 0xf5, 0x0e, 0xe2, 0xf7, 0xff, 0x77, 0x94, 0xfc, 0x8e, 0xea, 0x02,
	0xda, 0x73, 0x42, 0x36, 0xd5, 0xd0, 0x44, 0x77, 0xb4, 0xa9, 0xee, 0x24, 0xbb, 0x9d, 0x9a, 0xea,
	0x76, 0xed, 0x53, 0x58, 0x4a, 0x44, 0x0c, 0x7d, 0xcf, 0x0d, 0x29, 0xba, 0x09, 0x19, 0x87, 0xd1,
	0x21, 0x57, 0x2b, 0xbe, 0x9c, 0x95, 0xc4, 0xef, 0xc6, 0x91, 0x87, 0x25, 0x5b, 0x7b, 0x08, 0xcb,
	0x4f, 0xe9, 0x80, 0xbe, 0xe5, 0x15, 0xdf, 0xf9, 0x2c, 0x12, 0x47, 0x31, 0xb7, 0xa8, 0x0c, 0x80,
	0xfb, 0xfb, 0x5d, 0x62, 0xb4, 0xbb, 0x07, 0x7d, 0x7d, 0x81, 0xdb, 0x5f, 0xb4, 0x8c, 0x89, 0xad,
	0xa1, 0x12, 0x14, 0x0e, 0xf0, 0x9e, 0x32, 0x53, 0x77, 0x0c, 0x58, 0x3d, 0xff, 0x33, 0x8f, 0x0b,
	0x42, 0xa7, 0x7b, 0xd0, 0x23, 0xbd, 0x7e, 0x13, 0x37, 0x3b, 0xe4, 0xe3, 0x47, 0x2f, 0x1a, 0xdd,
	0x9e, 0xbe, 0x80, 0x96, 0xa0, 0x22, 0xf0, 0xfd, 0x4e, 0xbb, 0x43, 0x1e, 0x3d, 0x78, 0xd1, 0xe8,
	0xe9, 0xda, 0x9d, 0xef, 0xd2, 0x51, 0xac, 0x39, 0x9f, 0x54, 0xe8, 0x2a, 0x54, 0x5b, 0xf5, 0x47,
	0x0f, 0xc8, 0x47, 0xf5, 0xed, 0x2e, 0xb9, 0xbf, 0xfd, 0xac, 0xdb, 0x23, 0xf7, 0xc9, 0xde, 0xce,
	0x97, 0x4d, 0xcc, 0x23, 0x5e, 0x83, 0xcb, 0x82, 0xbd, 0xb7, 0xfd, 0x78, 0x96, 0xd6, 0xa2, 0xc3,
	0x0f, 0x1f, 0x6c, 0x77, 0x49, 0xfd, 0x21, 0x67, 0xeb, 0x13, 0x36, 0x85, 0xae, 0xc0, 0xca, 0x74,
	0xe8, 0x7b, 0x92, 0xd5, 0xd3, 0xd1, 0xd1, 0x78, 0xe4, 0x09, 0xbb, 0x88, 0xd6, 0xe1, 0xc3, 0xf3,
	0xb2, 0x22, 0x2d, 0xe3, 0x79, 0x8b, 0xec, 0x77, 0xfa, 0x46, 0xa7, 0xad, 0x67, 0xd0, 0x06, 0xdc,
	0x3c, 0x37, 0xc3, 0x84, 0x6b, 0x36, 0x0a, 0x3a, 0x27, 0xdb, 0x84, 0x67, 0x0e, 0xdd, 0x86, 0x1b,
	0xe7, 0x64, 0x9e, 0x70, 0xcc, 0x47, 0x21, 0xe7, 0x54, 0x91, 0xf0, 0x2c, 0xd4, 0xff, 0xd0, 0x20,
	0xa7, 0xae, 0x01, 0x3d, 0x81, 0x52, 0xe2, 0x2f, 0x1a, 0xaa, 0xf2, 0xe1, 0x9b, 0xf7, 0xaf, 0x6d,
	0x75, 0x7a, 0x2c, 0xf9, 0xd9, 0x84, 0xe4, 0xc8, 0xb3, 0xf3, 0x54, 0x68, 0xf6, 0xec, 0xe7, 0x50,
	0x8c, 0x6d, 0x02, 0xba, 0xc4, 0xf9, 0xd9, 0x65, 0x5b, 0x5d, 0x99, 0xc1, 0xd5, 0xca, 0x3c, 0x81,
	0x52, 0x62, 0x17, 0xe4, 0xbb, 0xe7, 0xad, 0xc7, 0xcc, 0xbb, 0x1b, 0x37, 0xbe, 0xfa, 0xe0, 0xd8,
	0x61, 0x27, 0xa3, 0xc3, 0x4d, 0xcb, 0x1b, 0x6e, 0x0d, 0x9c, 0xd1, 0x89, 0xe9, 0x0c, 0xbc, 0x53,
	0xba, 0x25, 0xfe, 0xb6, 0x5a, 0xde, 0x60, 0x8b, 0x59, 0x87, 0x59, 0x61, 0xdc, 0xff, 0x33, 0x00,
	0x00, 0xff, 0xff, 0x55, 0x24, 0x6b, 0x23, 0xec, 0x0e, 0x00, 0x00,
}
