// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tc_room.proto

package tc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateRoomRequest struct {
	// name of the room
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// number of seconds to keep the room open if no one joins
	EmptyTimeout uint32 `protobuf:"varint,2,opt,name=empty_timeout,json=emptyTimeout,proto3" json:"empty_timeout,omitempty"`
	// limit number of participants that can be in a room
	MaxParticipants uint32 `protobuf:"varint,3,opt,name=max_participants,json=maxParticipants,proto3" json:"max_participants,omitempty"`
	// override the node room is allocated to, for debugging
	NodeId string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// metadata of room
	Metadata string `protobuf:"bytes,5,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// egress
	Egress *RoomEgress `protobuf:"bytes,6,opt,name=egress,proto3" json:"egress,omitempty"`
	// playout delay of subscriber
	MinPlayoutDelay uint32 `protobuf:"varint,7,opt,name=min_playout_delay,json=minPlayoutDelay,proto3" json:"min_playout_delay,omitempty"`
	MaxPlayoutDelay uint32 `protobuf:"varint,8,opt,name=max_playout_delay,json=maxPlayoutDelay,proto3" json:"max_playout_delay,omitempty"`
	// improves A/V sync when playout_delay set to a value larger than 200ms. It will disables transceiver re-use
	// so not recommended for rooms with frequent subscription changes
	SyncStreams          bool     `protobuf:"varint,9,opt,name=sync_streams,json=syncStreams,proto3" json:"sync_streams,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateRoomRequest) Reset()         { *m = CreateRoomRequest{} }
func (m *CreateRoomRequest) String() string { return proto.CompactTextString(m) }
func (*CreateRoomRequest) ProtoMessage()    {}
func (*CreateRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{0}
}

func (m *CreateRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateRoomRequest.Unmarshal(m, b)
}
func (m *CreateRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateRoomRequest.Marshal(b, m, deterministic)
}
func (m *CreateRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateRoomRequest.Merge(m, src)
}
func (m *CreateRoomRequest) XXX_Size() int {
	return xxx_messageInfo_CreateRoomRequest.Size(m)
}
func (m *CreateRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateRoomRequest proto.InternalMessageInfo

func (m *CreateRoomRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateRoomRequest) GetEmptyTimeout() uint32 {
	if m != nil {
		return m.EmptyTimeout
	}
	return 0
}

func (m *CreateRoomRequest) GetMaxParticipants() uint32 {
	if m != nil {
		return m.MaxParticipants
	}
	return 0
}

func (m *CreateRoomRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *CreateRoomRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *CreateRoomRequest) GetEgress() *RoomEgress {
	if m != nil {
		return m.Egress
	}
	return nil
}

func (m *CreateRoomRequest) GetMinPlayoutDelay() uint32 {
	if m != nil {
		return m.MinPlayoutDelay
	}
	return 0
}

func (m *CreateRoomRequest) GetMaxPlayoutDelay() uint32 {
	if m != nil {
		return m.MaxPlayoutDelay
	}
	return 0
}

func (m *CreateRoomRequest) GetSyncStreams() bool {
	if m != nil {
		return m.SyncStreams
	}
	return false
}

type RoomEgress struct {
	Room                 *RoomCompositeEgressRequest `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Participant          *AutoParticipantEgress      `protobuf:"bytes,3,opt,name=participant,proto3" json:"participant,omitempty"`
	Tracks               *AutoTrackEgress            `protobuf:"bytes,2,opt,name=tracks,proto3" json:"tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *RoomEgress) Reset()         { *m = RoomEgress{} }
func (m *RoomEgress) String() string { return proto.CompactTextString(m) }
func (*RoomEgress) ProtoMessage()    {}
func (*RoomEgress) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{1}
}

func (m *RoomEgress) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomEgress.Unmarshal(m, b)
}
func (m *RoomEgress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomEgress.Marshal(b, m, deterministic)
}
func (m *RoomEgress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomEgress.Merge(m, src)
}
func (m *RoomEgress) XXX_Size() int {
	return xxx_messageInfo_RoomEgress.Size(m)
}
func (m *RoomEgress) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomEgress.DiscardUnknown(m)
}

var xxx_messageInfo_RoomEgress proto.InternalMessageInfo

func (m *RoomEgress) GetRoom() *RoomCompositeEgressRequest {
	if m != nil {
		return m.Room
	}
	return nil
}

func (m *RoomEgress) GetParticipant() *AutoParticipantEgress {
	if m != nil {
		return m.Participant
	}
	return nil
}

func (m *RoomEgress) GetTracks() *AutoTrackEgress {
	if m != nil {
		return m.Tracks
	}
	return nil
}

type ListRoomsRequest struct {
	// when set, will only return rooms with name match
	Names                []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoomsRequest) Reset()         { *m = ListRoomsRequest{} }
func (m *ListRoomsRequest) String() string { return proto.CompactTextString(m) }
func (*ListRoomsRequest) ProtoMessage()    {}
func (*ListRoomsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{2}
}

func (m *ListRoomsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoomsRequest.Unmarshal(m, b)
}
func (m *ListRoomsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoomsRequest.Marshal(b, m, deterministic)
}
func (m *ListRoomsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoomsRequest.Merge(m, src)
}
func (m *ListRoomsRequest) XXX_Size() int {
	return xxx_messageInfo_ListRoomsRequest.Size(m)
}
func (m *ListRoomsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoomsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoomsRequest proto.InternalMessageInfo

func (m *ListRoomsRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

type ListRoomsResponse struct {
	Rooms                []*Room  `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListRoomsResponse) Reset()         { *m = ListRoomsResponse{} }
func (m *ListRoomsResponse) String() string { return proto.CompactTextString(m) }
func (*ListRoomsResponse) ProtoMessage()    {}
func (*ListRoomsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{3}
}

func (m *ListRoomsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListRoomsResponse.Unmarshal(m, b)
}
func (m *ListRoomsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListRoomsResponse.Marshal(b, m, deterministic)
}
func (m *ListRoomsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListRoomsResponse.Merge(m, src)
}
func (m *ListRoomsResponse) XXX_Size() int {
	return xxx_messageInfo_ListRoomsResponse.Size(m)
}
func (m *ListRoomsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListRoomsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListRoomsResponse proto.InternalMessageInfo

func (m *ListRoomsResponse) GetRooms() []*Room {
	if m != nil {
		return m.Rooms
	}
	return nil
}

type DeleteRoomRequest struct {
	// name of the room
	Room                 string   `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoomRequest) Reset()         { *m = DeleteRoomRequest{} }
func (m *DeleteRoomRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteRoomRequest) ProtoMessage()    {}
func (*DeleteRoomRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{4}
}

func (m *DeleteRoomRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoomRequest.Unmarshal(m, b)
}
func (m *DeleteRoomRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoomRequest.Marshal(b, m, deterministic)
}
func (m *DeleteRoomRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoomRequest.Merge(m, src)
}
func (m *DeleteRoomRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteRoomRequest.Size(m)
}
func (m *DeleteRoomRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoomRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoomRequest proto.InternalMessageInfo

func (m *DeleteRoomRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

type DeleteRoomResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteRoomResponse) Reset()         { *m = DeleteRoomResponse{} }
func (m *DeleteRoomResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteRoomResponse) ProtoMessage()    {}
func (*DeleteRoomResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{5}
}

func (m *DeleteRoomResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteRoomResponse.Unmarshal(m, b)
}
func (m *DeleteRoomResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteRoomResponse.Marshal(b, m, deterministic)
}
func (m *DeleteRoomResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteRoomResponse.Merge(m, src)
}
func (m *DeleteRoomResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteRoomResponse.Size(m)
}
func (m *DeleteRoomResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteRoomResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteRoomResponse proto.InternalMessageInfo

type ListParticipantsRequest struct {
	// name of the room
	Room                 string   `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListParticipantsRequest) Reset()         { *m = ListParticipantsRequest{} }
func (m *ListParticipantsRequest) String() string { return proto.CompactTextString(m) }
func (*ListParticipantsRequest) ProtoMessage()    {}
func (*ListParticipantsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{6}
}

func (m *ListParticipantsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParticipantsRequest.Unmarshal(m, b)
}
func (m *ListParticipantsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParticipantsRequest.Marshal(b, m, deterministic)
}
func (m *ListParticipantsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParticipantsRequest.Merge(m, src)
}
func (m *ListParticipantsRequest) XXX_Size() int {
	return xxx_messageInfo_ListParticipantsRequest.Size(m)
}
func (m *ListParticipantsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParticipantsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListParticipantsRequest proto.InternalMessageInfo

func (m *ListParticipantsRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

type ListParticipantsResponse struct {
	Participants         []*ParticipantInfo `protobuf:"bytes,1,rep,name=participants,proto3" json:"participants,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ListParticipantsResponse) Reset()         { *m = ListParticipantsResponse{} }
func (m *ListParticipantsResponse) String() string { return proto.CompactTextString(m) }
func (*ListParticipantsResponse) ProtoMessage()    {}
func (*ListParticipantsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{7}
}

func (m *ListParticipantsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListParticipantsResponse.Unmarshal(m, b)
}
func (m *ListParticipantsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListParticipantsResponse.Marshal(b, m, deterministic)
}
func (m *ListParticipantsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListParticipantsResponse.Merge(m, src)
}
func (m *ListParticipantsResponse) XXX_Size() int {
	return xxx_messageInfo_ListParticipantsResponse.Size(m)
}
func (m *ListParticipantsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListParticipantsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListParticipantsResponse proto.InternalMessageInfo

func (m *ListParticipantsResponse) GetParticipants() []*ParticipantInfo {
	if m != nil {
		return m.Participants
	}
	return nil
}

type RoomParticipantIdentity struct {
	// name of the room
	Room string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// identity of the participant
	Identity             string   `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomParticipantIdentity) Reset()         { *m = RoomParticipantIdentity{} }
func (m *RoomParticipantIdentity) String() string { return proto.CompactTextString(m) }
func (*RoomParticipantIdentity) ProtoMessage()    {}
func (*RoomParticipantIdentity) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{8}
}

func (m *RoomParticipantIdentity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomParticipantIdentity.Unmarshal(m, b)
}
func (m *RoomParticipantIdentity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomParticipantIdentity.Marshal(b, m, deterministic)
}
func (m *RoomParticipantIdentity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomParticipantIdentity.Merge(m, src)
}
func (m *RoomParticipantIdentity) XXX_Size() int {
	return xxx_messageInfo_RoomParticipantIdentity.Size(m)
}
func (m *RoomParticipantIdentity) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomParticipantIdentity.DiscardUnknown(m)
}

var xxx_messageInfo_RoomParticipantIdentity proto.InternalMessageInfo

func (m *RoomParticipantIdentity) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *RoomParticipantIdentity) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

type RemoveParticipantResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveParticipantResponse) Reset()         { *m = RemoveParticipantResponse{} }
func (m *RemoveParticipantResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveParticipantResponse) ProtoMessage()    {}
func (*RemoveParticipantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{9}
}

func (m *RemoveParticipantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveParticipantResponse.Unmarshal(m, b)
}
func (m *RemoveParticipantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveParticipantResponse.Marshal(b, m, deterministic)
}
func (m *RemoveParticipantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveParticipantResponse.Merge(m, src)
}
func (m *RemoveParticipantResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveParticipantResponse.Size(m)
}
func (m *RemoveParticipantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveParticipantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveParticipantResponse proto.InternalMessageInfo

type MuteRoomTrackRequest struct {
	// name of the room
	Room     string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Identity string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// sid of the track to mute
	TrackSid string `protobuf:"bytes,3,opt,name=track_sid,json=trackSid,proto3" json:"track_sid,omitempty"`
	// set to true to mute, false to unmute
	Muted                bool     `protobuf:"varint,4,opt,name=muted,proto3" json:"muted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MuteRoomTrackRequest) Reset()         { *m = MuteRoomTrackRequest{} }
func (m *MuteRoomTrackRequest) String() string { return proto.CompactTextString(m) }
func (*MuteRoomTrackRequest) ProtoMessage()    {}
func (*MuteRoomTrackRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{10}
}

func (m *MuteRoomTrackRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MuteRoomTrackRequest.Unmarshal(m, b)
}
func (m *MuteRoomTrackRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MuteRoomTrackRequest.Marshal(b, m, deterministic)
}
func (m *MuteRoomTrackRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MuteRoomTrackRequest.Merge(m, src)
}
func (m *MuteRoomTrackRequest) XXX_Size() int {
	return xxx_messageInfo_MuteRoomTrackRequest.Size(m)
}
func (m *MuteRoomTrackRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MuteRoomTrackRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MuteRoomTrackRequest proto.InternalMessageInfo

func (m *MuteRoomTrackRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *MuteRoomTrackRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *MuteRoomTrackRequest) GetTrackSid() string {
	if m != nil {
		return m.TrackSid
	}
	return ""
}

func (m *MuteRoomTrackRequest) GetMuted() bool {
	if m != nil {
		return m.Muted
	}
	return false
}

type MuteRoomTrackResponse struct {
	Track                *TrackInfo `protobuf:"bytes,1,opt,name=track,proto3" json:"track,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MuteRoomTrackResponse) Reset()         { *m = MuteRoomTrackResponse{} }
func (m *MuteRoomTrackResponse) String() string { return proto.CompactTextString(m) }
func (*MuteRoomTrackResponse) ProtoMessage()    {}
func (*MuteRoomTrackResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{11}
}

func (m *MuteRoomTrackResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MuteRoomTrackResponse.Unmarshal(m, b)
}
func (m *MuteRoomTrackResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MuteRoomTrackResponse.Marshal(b, m, deterministic)
}
func (m *MuteRoomTrackResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MuteRoomTrackResponse.Merge(m, src)
}
func (m *MuteRoomTrackResponse) XXX_Size() int {
	return xxx_messageInfo_MuteRoomTrackResponse.Size(m)
}
func (m *MuteRoomTrackResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MuteRoomTrackResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MuteRoomTrackResponse proto.InternalMessageInfo

func (m *MuteRoomTrackResponse) GetTrack() *TrackInfo {
	if m != nil {
		return m.Track
	}
	return nil
}

type UpdateParticipantRequest struct {
	Room     string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Identity string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// metadata to update. skipping updates if left empty
	Metadata string `protobuf:"bytes,3,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// set to update the participant's permissions
	Permission *ParticipantPermission `protobuf:"bytes,4,opt,name=permission,proto3" json:"permission,omitempty"`
	// display name to update
	Name                 string   `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateParticipantRequest) Reset()         { *m = UpdateParticipantRequest{} }
func (m *UpdateParticipantRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateParticipantRequest) ProtoMessage()    {}
func (*UpdateParticipantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{12}
}

func (m *UpdateParticipantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateParticipantRequest.Unmarshal(m, b)
}
func (m *UpdateParticipantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateParticipantRequest.Marshal(b, m, deterministic)
}
func (m *UpdateParticipantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateParticipantRequest.Merge(m, src)
}
func (m *UpdateParticipantRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateParticipantRequest.Size(m)
}
func (m *UpdateParticipantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateParticipantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateParticipantRequest proto.InternalMessageInfo

func (m *UpdateParticipantRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *UpdateParticipantRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *UpdateParticipantRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func (m *UpdateParticipantRequest) GetPermission() *ParticipantPermission {
	if m != nil {
		return m.Permission
	}
	return nil
}

func (m *UpdateParticipantRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UpdateSubscriptionsRequest struct {
	Room     string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Identity string `protobuf:"bytes,2,opt,name=identity,proto3" json:"identity,omitempty"`
	// list of sids of tracks
	TrackSids []string `protobuf:"bytes,3,rep,name=track_sids,json=trackSids,proto3" json:"track_sids,omitempty"`
	// set to true to subscribe, false to unsubscribe from tracks
	Subscribe bool `protobuf:"varint,4,opt,name=subscribe,proto3" json:"subscribe,omitempty"`
	// list of participants and their tracks
	ParticipantTracks    []*ParticipantTracks `protobuf:"bytes,5,rep,name=participant_tracks,json=participantTracks,proto3" json:"participant_tracks,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *UpdateSubscriptionsRequest) Reset()         { *m = UpdateSubscriptionsRequest{} }
func (m *UpdateSubscriptionsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSubscriptionsRequest) ProtoMessage()    {}
func (*UpdateSubscriptionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{13}
}

func (m *UpdateSubscriptionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSubscriptionsRequest.Unmarshal(m, b)
}
func (m *UpdateSubscriptionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSubscriptionsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSubscriptionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSubscriptionsRequest.Merge(m, src)
}
func (m *UpdateSubscriptionsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSubscriptionsRequest.Size(m)
}
func (m *UpdateSubscriptionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSubscriptionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSubscriptionsRequest proto.InternalMessageInfo

func (m *UpdateSubscriptionsRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *UpdateSubscriptionsRequest) GetIdentity() string {
	if m != nil {
		return m.Identity
	}
	return ""
}

func (m *UpdateSubscriptionsRequest) GetTrackSids() []string {
	if m != nil {
		return m.TrackSids
	}
	return nil
}

func (m *UpdateSubscriptionsRequest) GetSubscribe() bool {
	if m != nil {
		return m.Subscribe
	}
	return false
}

func (m *UpdateSubscriptionsRequest) GetParticipantTracks() []*ParticipantTracks {
	if m != nil {
		return m.ParticipantTracks
	}
	return nil
}

type UpdateSubscriptionsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSubscriptionsResponse) Reset()         { *m = UpdateSubscriptionsResponse{} }
func (m *UpdateSubscriptionsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateSubscriptionsResponse) ProtoMessage()    {}
func (*UpdateSubscriptionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{14}
}

func (m *UpdateSubscriptionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSubscriptionsResponse.Unmarshal(m, b)
}
func (m *UpdateSubscriptionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSubscriptionsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateSubscriptionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSubscriptionsResponse.Merge(m, src)
}
func (m *UpdateSubscriptionsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateSubscriptionsResponse.Size(m)
}
func (m *UpdateSubscriptionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSubscriptionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSubscriptionsResponse proto.InternalMessageInfo

type SendDataRequest struct {
	Room string          `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	Data []byte          `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Kind DataPacket_Kind `protobuf:"varint,3,opt,name=kind,proto3,enum=tc.DataPacket_Kind" json:"kind,omitempty"`
	// mark deprecated
	DestinationSids []string `protobuf:"bytes,4,rep,name=destination_sids,json=destinationSids,proto3" json:"destination_sids,omitempty"` // Deprecated: Do not use.
	// when set, only forward to these identities
	DestinationIdentities []string `protobuf:"bytes,6,rep,name=destination_identities,json=destinationIdentities,proto3" json:"destination_identities,omitempty"`
	Topic                 string   `protobuf:"bytes,5,opt,name=topic,proto3" json:"topic,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *SendDataRequest) Reset()         { *m = SendDataRequest{} }
func (m *SendDataRequest) String() string { return proto.CompactTextString(m) }
func (*SendDataRequest) ProtoMessage()    {}
func (*SendDataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{15}
}

func (m *SendDataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataRequest.Unmarshal(m, b)
}
func (m *SendDataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataRequest.Marshal(b, m, deterministic)
}
func (m *SendDataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataRequest.Merge(m, src)
}
func (m *SendDataRequest) XXX_Size() int {
	return xxx_messageInfo_SendDataRequest.Size(m)
}
func (m *SendDataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataRequest proto.InternalMessageInfo

func (m *SendDataRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *SendDataRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *SendDataRequest) GetKind() DataPacket_Kind {
	if m != nil {
		return m.Kind
	}
	return DataPacket_RELIABLE
}

// Deprecated: Do not use.
func (m *SendDataRequest) GetDestinationSids() []string {
	if m != nil {
		return m.DestinationSids
	}
	return nil
}

func (m *SendDataRequest) GetDestinationIdentities() []string {
	if m != nil {
		return m.DestinationIdentities
	}
	return nil
}

func (m *SendDataRequest) GetTopic() string {
	if m != nil {
		return m.Topic
	}
	return ""
}

type SendDataResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendDataResponse) Reset()         { *m = SendDataResponse{} }
func (m *SendDataResponse) String() string { return proto.CompactTextString(m) }
func (*SendDataResponse) ProtoMessage()    {}
func (*SendDataResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{16}
}

func (m *SendDataResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendDataResponse.Unmarshal(m, b)
}
func (m *SendDataResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendDataResponse.Marshal(b, m, deterministic)
}
func (m *SendDataResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendDataResponse.Merge(m, src)
}
func (m *SendDataResponse) XXX_Size() int {
	return xxx_messageInfo_SendDataResponse.Size(m)
}
func (m *SendDataResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SendDataResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SendDataResponse proto.InternalMessageInfo

type UpdateRoomMetadataRequest struct {
	Room string `protobuf:"bytes,1,opt,name=room,proto3" json:"room,omitempty"`
	// metadata to update. skipping updates if left empty
	Metadata             string   `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateRoomMetadataRequest) Reset()         { *m = UpdateRoomMetadataRequest{} }
func (m *UpdateRoomMetadataRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateRoomMetadataRequest) ProtoMessage()    {}
func (*UpdateRoomMetadataRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_75857016c2abbc71, []int{17}
}

func (m *UpdateRoomMetadataRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateRoomMetadataRequest.Unmarshal(m, b)
}
func (m *UpdateRoomMetadataRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateRoomMetadataRequest.Marshal(b, m, deterministic)
}
func (m *UpdateRoomMetadataRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateRoomMetadataRequest.Merge(m, src)
}
func (m *UpdateRoomMetadataRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateRoomMetadataRequest.Size(m)
}
func (m *UpdateRoomMetadataRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateRoomMetadataRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateRoomMetadataRequest proto.InternalMessageInfo

func (m *UpdateRoomMetadataRequest) GetRoom() string {
	if m != nil {
		return m.Room
	}
	return ""
}

func (m *UpdateRoomMetadataRequest) GetMetadata() string {
	if m != nil {
		return m.Metadata
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateRoomRequest)(nil), "tc.CreateRoomRequest")
	proto.RegisterType((*RoomEgress)(nil), "tc.RoomEgress")
	proto.RegisterType((*ListRoomsRequest)(nil), "tc.ListRoomsRequest")
	proto.RegisterType((*ListRoomsResponse)(nil), "tc.ListRoomsResponse")
	proto.RegisterType((*DeleteRoomRequest)(nil), "tc.DeleteRoomRequest")
	proto.RegisterType((*DeleteRoomResponse)(nil), "tc.DeleteRoomResponse")
	proto.RegisterType((*ListParticipantsRequest)(nil), "tc.ListParticipantsRequest")
	proto.RegisterType((*ListParticipantsResponse)(nil), "tc.ListParticipantsResponse")
	proto.RegisterType((*RoomParticipantIdentity)(nil), "tc.RoomParticipantIdentity")
	proto.RegisterType((*RemoveParticipantResponse)(nil), "tc.RemoveParticipantResponse")
	proto.RegisterType((*MuteRoomTrackRequest)(nil), "tc.MuteRoomTrackRequest")
	proto.RegisterType((*MuteRoomTrackResponse)(nil), "tc.MuteRoomTrackResponse")
	proto.RegisterType((*UpdateParticipantRequest)(nil), "tc.UpdateParticipantRequest")
	proto.RegisterType((*UpdateSubscriptionsRequest)(nil), "tc.UpdateSubscriptionsRequest")
	proto.RegisterType((*UpdateSubscriptionsResponse)(nil), "tc.UpdateSubscriptionsResponse")
	proto.RegisterType((*SendDataRequest)(nil), "tc.SendDataRequest")
	proto.RegisterType((*SendDataResponse)(nil), "tc.SendDataResponse")
	proto.RegisterType((*UpdateRoomMetadataRequest)(nil), "tc.UpdateRoomMetadataRequest")
}

func init() { proto.RegisterFile("tc_room.proto", fileDescriptor_75857016c2abbc71) }

var fileDescriptor_75857016c2abbc71 = []byte{
	// 1031 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xcd, 0x6e, 0xdb, 0x46,
	0x10, 0x06, 0x6d, 0xc9, 0x11, 0x47, 0xfe, 0xd3, 0xc6, 0x8e, 0x69, 0x3a, 0x76, 0x15, 0x1a, 0x68,
	0xd4, 0x16, 0x96, 0x01, 0x05, 0x41, 0x5b, 0xa4, 0x3d, 0xd4, 0x71, 0x5b, 0x08, 0xa9, 0x51, 0x81,
	0x4a, 0x7b, 0xe8, 0x85, 0xa0, 0xc8, 0x6d, 0xbc, 0xb0, 0xc8, 0x65, 0xb9, 0x4b, 0x23, 0x7a, 0xa5,
	0xde, 0xfb, 0x1c, 0x79, 0x83, 0x3e, 0x47, 0x8f, 0xc5, 0xfe, 0x88, 0x5c, 0x49, 0xb4, 0x02, 0xe4,
	0xa6, 0xfd, 0x66, 0x76, 0x67, 0xe6, 0x9b, 0x99, 0x8f, 0x82, 0x1d, 0x1e, 0x05, 0x39, 0xa5, 0x49,
	0x3f, 0xcb, 0x29, 0xa7, 0x68, 0x83, 0x47, 0xee, 0x1e, 0x8f, 0x82, 0x84, 0xc6, 0x78, 0xca, 0x14,
	0x28, 0x01, 0xfc, 0x2e, 0xc7, 0x4c, 0x03, 0xde, 0x87, 0x0d, 0xe8, 0xbc, 0xce, 0x71, 0xc8, 0xb1,
	0x4f, 0x69, 0xe2, 0xe3, 0xbf, 0x0a, 0xcc, 0x38, 0x42, 0xd0, 0x48, 0xc3, 0x04, 0x3b, 0x56, 0xd7,
	0xea, 0xd9, 0xbe, 0xfc, 0x8d, 0xce, 0x61, 0x07, 0x27, 0x19, 0x9f, 0x05, 0x9c, 0x24, 0x98, 0x16,
	0xdc, 0xd9, 0xe8, 0x5a, 0xbd, 0x1d, 0x7f, 0x5b, 0x82, 0x6f, 0x15, 0x86, 0xbe, 0x80, 0xfd, 0x24,
	0x7c, 0x1f, 0x64, 0x61, 0xce, 0x49, 0x44, 0xb2, 0x30, 0xe5, 0xcc, 0xd9, 0x94, 0x7e, 0x7b, 0x49,
	0xf8, 0x7e, 0x64, 0xc0, 0xe8, 0x08, 0x1e, 0xa5, 0x34, 0xc6, 0x01, 0x89, 0x9d, 0x86, 0x0c, 0xb3,
	0x25, 0x8e, 0xc3, 0x18, 0xb9, 0xd0, 0x4a, 0x30, 0x0f, 0xe3, 0x90, 0x87, 0x4e, 0x53, 0x5a, 0xca,
	0x33, 0xfa, 0x1c, 0xb6, 0x54, 0xfa, 0xce, 0x56, 0xd7, 0xea, 0xb5, 0x07, 0xbb, 0x7d, 0x1e, 0xf5,
	0x45, 0xe6, 0x3f, 0x4a, 0xd4, 0xd7, 0x56, 0xf4, 0x25, 0x74, 0x12, 0x92, 0x06, 0xd9, 0x34, 0x9c,
	0xd1, 0x82, 0x07, 0x31, 0x9e, 0x86, 0x33, 0xe7, 0x91, 0x4e, 0x84, 0xa4, 0x23, 0x85, 0x5f, 0x0b,
	0x58, 0xfa, 0x8a, 0x9c, 0x17, 0x7c, 0x5b, 0x55, 0xd2, 0xa6, 0xef, 0x33, 0xd8, 0x66, 0xb3, 0x34,
	0x0a, 0x18, 0xcf, 0x71, 0x98, 0x30, 0xc7, 0xee, 0x5a, 0xbd, 0x96, 0xdf, 0x16, 0xd8, 0x58, 0x41,
	0xde, 0xdf, 0x16, 0x40, 0x95, 0x11, 0x1a, 0x40, 0x43, 0x34, 0x45, 0x52, 0xd9, 0x1e, 0x9c, 0xcd,
	0xf3, 0x7d, 0x4d, 0x93, 0x8c, 0x32, 0xc2, 0xb1, 0x4e, 0x5c, 0x11, 0xef, 0x4b, 0x5f, 0xf4, 0x0a,
	0xda, 0x06, 0x83, 0x92, 0xc0, 0xf6, 0xe0, 0x58, 0x5c, 0xfd, 0xa1, 0xe0, 0xd4, 0x60, 0x51, 0x5f,
	0x36, 0xbd, 0xd1, 0x57, 0xb0, 0xc5, 0xf3, 0x30, 0xba, 0x63, 0xb2, 0x41, 0xed, 0xc1, 0xe3, 0xf9,
	0xbd, 0xb7, 0x02, 0x9d, 0xf3, 0xa4, 0x5c, 0xbc, 0x1e, 0xec, 0xff, 0x42, 0x18, 0x17, 0x19, 0xcd,
	0x73, 0x40, 0x07, 0xd0, 0x14, 0x0d, 0x67, 0x8e, 0xd5, 0xdd, 0xec, 0xd9, 0xbe, 0x3a, 0x78, 0x2f,
	0xa0, 0x63, 0x78, 0xb2, 0x8c, 0xa6, 0x0c, 0xa3, 0x33, 0x68, 0x8a, 0x84, 0x95, 0x6b, 0x7b, 0xd0,
	0x9a, 0x57, 0xe7, 0x2b, 0xd8, 0x7b, 0x0e, 0x9d, 0x6b, 0x3c, 0xc5, 0x2b, 0xc3, 0x55, 0x32, 0x62,
	0xab, 0x8a, 0xbd, 0x03, 0x40, 0xa6, 0xa3, 0x7a, 0xde, 0xbb, 0x80, 0x23, 0x11, 0xd3, 0x1c, 0x9b,
	0x75, 0x8f, 0x8c, 0xc1, 0x59, 0x75, 0xd7, 0x99, 0x7e, 0x0d, 0xdb, 0x0b, 0x43, 0xa9, 0x12, 0x96,
	0xdc, 0x18, 0xfe, 0xc3, 0xf4, 0x4f, 0xea, 0x2f, 0x38, 0x7a, 0x43, 0x38, 0x12, 0x39, 0x99, 0x4e,
	0x31, 0x4e, 0x39, 0xe1, 0xb3, 0xba, 0x1c, 0xc4, 0xf0, 0x12, 0x6d, 0x97, 0xfc, 0xdb, 0x7e, 0x79,
	0xf6, 0x4e, 0xe0, 0xd8, 0xc7, 0x09, 0xbd, 0xc7, 0xc6, 0x63, 0x65, 0xad, 0x33, 0x38, 0xb8, 0x29,
	0x54, 0xfd, 0xb2, 0x51, 0x6b, 0x0a, 0x5d, 0x17, 0x04, 0x9d, 0x80, 0x2d, 0x7b, 0x1b, 0x30, 0x12,
	0xcb, 0xc9, 0xb1, 0xfd, 0x96, 0x04, 0xc6, 0x24, 0x16, 0xad, 0x4d, 0x0a, 0x8e, 0xd5, 0xc6, 0xb5,
	0x7c, 0x75, 0xf0, 0xbe, 0x83, 0xc3, 0xa5, 0xd0, 0x9a, 0xb4, 0x73, 0x68, 0xca, 0xab, 0x7a, 0x78,
	0x77, 0x04, 0x5b, 0xd2, 0x43, 0xf2, 0xa4, 0x6c, 0xde, 0x3f, 0x16, 0x38, 0xbf, 0x65, 0x71, 0xc8,
	0x17, 0xcb, 0xfa, 0xb4, 0xec, 0xcd, 0xdd, 0xdf, 0x5c, 0xda, 0xfd, 0x6f, 0x01, 0x32, 0x9c, 0x27,
	0x84, 0x31, 0x42, 0x53, 0x59, 0x81, 0x5e, 0x0a, 0x23, 0xee, 0xa8, 0x74, 0xf0, 0x0d, 0xe7, 0x52,
	0xcf, 0x9a, 0x95, 0x9e, 0x79, 0x1f, 0x2c, 0x70, 0x55, 0xde, 0xe3, 0x62, 0xc2, 0xa2, 0x9c, 0x64,
	0x9c, 0xd0, 0x94, 0x7d, 0x6a, 0xe6, 0xa7, 0x00, 0x25, 0xef, 0x42, 0xf3, 0xc4, 0xea, 0xd8, 0x73,
	0xe2, 0x19, 0x7a, 0x0a, 0x36, 0x53, 0x61, 0x26, 0x58, 0xb3, 0x5f, 0x01, 0xe8, 0x1a, 0x90, 0x31,
	0x74, 0x81, 0xde, 0xdf, 0xa6, 0x9c, 0xd1, 0xc3, 0xa5, 0x12, 0x65, 0x03, 0x98, 0xdf, 0xc9, 0x96,
	0x21, 0xef, 0x14, 0x4e, 0x6a, 0x0b, 0xd2, 0x13, 0xf6, 0xaf, 0x05, 0x7b, 0x63, 0x9c, 0xc6, 0xd7,
	0x21, 0x0f, 0xd7, 0x55, 0x89, 0xa0, 0x21, 0xf9, 0x17, 0x15, 0x6e, 0xfb, 0xf2, 0x37, 0x7a, 0x0e,
	0x8d, 0x3b, 0x92, 0xaa, 0x81, 0xda, 0x55, 0x6b, 0x23, 0x9e, 0x19, 0x85, 0xd1, 0x1d, 0xe6, 0xfd,
	0x37, 0x24, 0x8d, 0x7d, 0xe9, 0x80, 0x2e, 0x60, 0x3f, 0xc6, 0x8c, 0x93, 0x34, 0x14, 0xc1, 0x15,
	0x19, 0x0d, 0x41, 0xc6, 0xd5, 0x86, 0x63, 0xf9, 0x7b, 0x86, 0x4d, 0xd2, 0xf2, 0x12, 0x9e, 0x98,
	0xee, 0x9a, 0x4d, 0x82, 0x85, 0xbe, 0x0b, 0x06, 0x0f, 0x0d, 0xeb, 0xb0, 0x34, 0x8a, 0x39, 0xe6,
	0x34, 0x23, 0x91, 0x6e, 0xa8, 0x3a, 0x78, 0x08, 0xf6, 0xab, 0xfa, 0x74, 0xd1, 0x6f, 0xe0, 0x58,
	0x71, 0x22, 0xa6, 0xfb, 0x46, 0x8f, 0xd2, 0x47, 0x7a, 0x5c, 0x4e, 0xe0, 0xc6, 0xe2, 0x04, 0x0e,
	0xfe, 0x6b, 0x42, 0x5b, 0xbc, 0x33, 0xc6, 0xf9, 0x3d, 0x89, 0x30, 0xba, 0x00, 0xa8, 0xbe, 0x9d,
	0x48, 0x36, 0x6a, 0xe5, 0x5b, 0xea, 0x96, 0xa2, 0x88, 0xbe, 0x01, 0xbb, 0x94, 0x50, 0x74, 0x20,
	0xe0, 0x65, 0xed, 0x75, 0x0f, 0x97, 0x50, 0xbd, 0x88, 0xaf, 0x00, 0x2a, 0x79, 0x54, 0x81, 0x56,
	0x74, 0xd5, 0x7d, 0xb2, 0x0c, 0xeb, 0xcb, 0x37, 0x4a, 0xe3, 0x17, 0x3e, 0xbe, 0x27, 0xf3, 0x38,
	0x35, 0xda, 0xea, 0x3e, 0xad, 0x37, 0xea, 0xe7, 0xae, 0x60, 0xf7, 0x67, 0x6c, 0x9a, 0xd4, 0x63,
	0x0f, 0x88, 0xa4, 0x5b, 0x27, 0xb1, 0xe8, 0x57, 0xe8, 0xac, 0x28, 0xe1, 0xfa, 0x67, 0x4e, 0xa5,
	0xf1, 0x21, 0xf5, 0x44, 0x43, 0x40, 0x42, 0xc2, 0x46, 0xc5, 0x64, 0x4a, 0xd8, 0x2d, 0x8e, 0xe5,
	0x46, 0x20, 0x47, 0x5c, 0xaa, 0x53, 0x55, 0xf7, 0xb8, 0xc6, 0xa2, 0x9f, 0xfa, 0x09, 0x3a, 0x2b,
	0x72, 0x86, 0x24, 0x25, 0x0f, 0xa9, 0x5c, 0x7d, 0x8d, 0xbf, 0xc3, 0xe3, 0x9a, 0x6d, 0x44, 0x67,
	0xd5, 0x4b, 0x75, 0xba, 0xe3, 0x7e, 0xf6, 0xa0, 0x5d, 0xe7, 0xf7, 0x12, 0x5a, 0xf3, 0x29, 0x47,
	0x32, 0xf0, 0xd2, 0x4e, 0xbb, 0x07, 0x8b, 0xa0, 0xbe, 0xf6, 0x3d, 0xa0, 0xd5, 0x45, 0x40, 0xa7,
	0x55, 0xb4, 0x9a, 0x05, 0xa9, 0x66, 0xf7, 0xea, 0xfc, 0x8f, 0x67, 0xef, 0x08, 0xbf, 0x2d, 0x26,
	0xfd, 0x88, 0x26, 0x97, 0x53, 0x52, 0xdc, 0x86, 0x64, 0x4a, 0xef, 0xf1, 0xa5, 0xfc, 0x1b, 0x19,
	0xd1, 0xe9, 0x25, 0x8f, 0x26, 0x5b, 0xf2, 0xf0, 0xe2, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0xa5,
	0x37, 0xe5, 0xf6, 0x8a, 0x0a, 0x00, 0x00,
}
