// Code generated by protoc-gen-go. DO NOT EDIT.
// source: tc_sip.proto

package tc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateSIPTrunkRequest struct {
	// CIDR or IPs that traffic is accepted from
	// An empty list means all inbound traffic is accepted.
	Addresses []string `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	// `To` value that will be used when making a call
	To string `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	// Accepted `To` values. This Trunk will only accept a call made to
	// these numbers. This allows you to have distinct Trunks for different phone
	// numbers at the same provider.
	// An empty list means all dialed numbers are accepted.
	AllowedDestinationsRegex []string `protobuf:"bytes,3,rep,name=allowed_destinations_regex,json=allowedDestinationsRegex,proto3" json:"allowed_destinations_regex,omitempty"`
	XXX_NoUnkeyedLiteral     struct{} `json:"-"`
	XXX_unrecognized         []byte   `json:"-"`
	XXX_sizecache            int32    `json:"-"`
}

func (m *CreateSIPTrunkRequest) Reset()         { *m = CreateSIPTrunkRequest{} }
func (m *CreateSIPTrunkRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSIPTrunkRequest) ProtoMessage()    {}
func (*CreateSIPTrunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{0}
}

func (m *CreateSIPTrunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSIPTrunkRequest.Unmarshal(m, b)
}
func (m *CreateSIPTrunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSIPTrunkRequest.Marshal(b, m, deterministic)
}
func (m *CreateSIPTrunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSIPTrunkRequest.Merge(m, src)
}
func (m *CreateSIPTrunkRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSIPTrunkRequest.Size(m)
}
func (m *CreateSIPTrunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSIPTrunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSIPTrunkRequest proto.InternalMessageInfo

func (m *CreateSIPTrunkRequest) GetAddresses() []string {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func (m *CreateSIPTrunkRequest) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *CreateSIPTrunkRequest) GetAllowedDestinationsRegex() []string {
	if m != nil {
		return m.AllowedDestinationsRegex
	}
	return nil
}

type SIPTrunkInfo struct {
	SipTrunkId           string   `protobuf:"bytes,1,opt,name=sip_trunk_id,json=sipTrunkId,proto3" json:"sip_trunk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIPTrunkInfo) Reset()         { *m = SIPTrunkInfo{} }
func (m *SIPTrunkInfo) String() string { return proto.CompactTextString(m) }
func (*SIPTrunkInfo) ProtoMessage()    {}
func (*SIPTrunkInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{1}
}

func (m *SIPTrunkInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIPTrunkInfo.Unmarshal(m, b)
}
func (m *SIPTrunkInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIPTrunkInfo.Marshal(b, m, deterministic)
}
func (m *SIPTrunkInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIPTrunkInfo.Merge(m, src)
}
func (m *SIPTrunkInfo) XXX_Size() int {
	return xxx_messageInfo_SIPTrunkInfo.Size(m)
}
func (m *SIPTrunkInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SIPTrunkInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SIPTrunkInfo proto.InternalMessageInfo

func (m *SIPTrunkInfo) GetSipTrunkId() string {
	if m != nil {
		return m.SipTrunkId
	}
	return ""
}

type ListSIPTrunkRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSIPTrunkRequest) Reset()         { *m = ListSIPTrunkRequest{} }
func (m *ListSIPTrunkRequest) String() string { return proto.CompactTextString(m) }
func (*ListSIPTrunkRequest) ProtoMessage()    {}
func (*ListSIPTrunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{2}
}

func (m *ListSIPTrunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSIPTrunkRequest.Unmarshal(m, b)
}
func (m *ListSIPTrunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSIPTrunkRequest.Marshal(b, m, deterministic)
}
func (m *ListSIPTrunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSIPTrunkRequest.Merge(m, src)
}
func (m *ListSIPTrunkRequest) XXX_Size() int {
	return xxx_messageInfo_ListSIPTrunkRequest.Size(m)
}
func (m *ListSIPTrunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSIPTrunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSIPTrunkRequest proto.InternalMessageInfo

type ListSIPTrunkResponse struct {
	Items                []*SIPTrunkInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListSIPTrunkResponse) Reset()         { *m = ListSIPTrunkResponse{} }
func (m *ListSIPTrunkResponse) String() string { return proto.CompactTextString(m) }
func (*ListSIPTrunkResponse) ProtoMessage()    {}
func (*ListSIPTrunkResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{3}
}

func (m *ListSIPTrunkResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSIPTrunkResponse.Unmarshal(m, b)
}
func (m *ListSIPTrunkResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSIPTrunkResponse.Marshal(b, m, deterministic)
}
func (m *ListSIPTrunkResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSIPTrunkResponse.Merge(m, src)
}
func (m *ListSIPTrunkResponse) XXX_Size() int {
	return xxx_messageInfo_ListSIPTrunkResponse.Size(m)
}
func (m *ListSIPTrunkResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSIPTrunkResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSIPTrunkResponse proto.InternalMessageInfo

func (m *ListSIPTrunkResponse) GetItems() []*SIPTrunkInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteSIPTrunkRequest struct {
	SipTrunkId           string   `protobuf:"bytes,1,opt,name=sip_trunk_id,json=sipTrunkId,proto3" json:"sip_trunk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSIPTrunkRequest) Reset()         { *m = DeleteSIPTrunkRequest{} }
func (m *DeleteSIPTrunkRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSIPTrunkRequest) ProtoMessage()    {}
func (*DeleteSIPTrunkRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{4}
}

func (m *DeleteSIPTrunkRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSIPTrunkRequest.Unmarshal(m, b)
}
func (m *DeleteSIPTrunkRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSIPTrunkRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSIPTrunkRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSIPTrunkRequest.Merge(m, src)
}
func (m *DeleteSIPTrunkRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSIPTrunkRequest.Size(m)
}
func (m *DeleteSIPTrunkRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSIPTrunkRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSIPTrunkRequest proto.InternalMessageInfo

func (m *DeleteSIPTrunkRequest) GetSipTrunkId() string {
	if m != nil {
		return m.SipTrunkId
	}
	return ""
}

type SIPDispatchRuleDirect struct {
	// What room should call be directed into
	RoomName string `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// Optional pin required to enter room
	Pin                  string   `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIPDispatchRuleDirect) Reset()         { *m = SIPDispatchRuleDirect{} }
func (m *SIPDispatchRuleDirect) String() string { return proto.CompactTextString(m) }
func (*SIPDispatchRuleDirect) ProtoMessage()    {}
func (*SIPDispatchRuleDirect) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{5}
}

func (m *SIPDispatchRuleDirect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIPDispatchRuleDirect.Unmarshal(m, b)
}
func (m *SIPDispatchRuleDirect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIPDispatchRuleDirect.Marshal(b, m, deterministic)
}
func (m *SIPDispatchRuleDirect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIPDispatchRuleDirect.Merge(m, src)
}
func (m *SIPDispatchRuleDirect) XXX_Size() int {
	return xxx_messageInfo_SIPDispatchRuleDirect.Size(m)
}
func (m *SIPDispatchRuleDirect) XXX_DiscardUnknown() {
	xxx_messageInfo_SIPDispatchRuleDirect.DiscardUnknown(m)
}

var xxx_messageInfo_SIPDispatchRuleDirect proto.InternalMessageInfo

func (m *SIPDispatchRuleDirect) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *SIPDispatchRuleDirect) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type SIPDispatchRulePin struct {
	// What room should call be directed into
	RoomName string `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// Pin required to enter room
	Pin                  string   `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIPDispatchRulePin) Reset()         { *m = SIPDispatchRulePin{} }
func (m *SIPDispatchRulePin) String() string { return proto.CompactTextString(m) }
func (*SIPDispatchRulePin) ProtoMessage()    {}
func (*SIPDispatchRulePin) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{6}
}

func (m *SIPDispatchRulePin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIPDispatchRulePin.Unmarshal(m, b)
}
func (m *SIPDispatchRulePin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIPDispatchRulePin.Marshal(b, m, deterministic)
}
func (m *SIPDispatchRulePin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIPDispatchRulePin.Merge(m, src)
}
func (m *SIPDispatchRulePin) XXX_Size() int {
	return xxx_messageInfo_SIPDispatchRulePin.Size(m)
}
func (m *SIPDispatchRulePin) XXX_DiscardUnknown() {
	xxx_messageInfo_SIPDispatchRulePin.DiscardUnknown(m)
}

var xxx_messageInfo_SIPDispatchRulePin proto.InternalMessageInfo

func (m *SIPDispatchRulePin) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *SIPDispatchRulePin) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type SIPDispatchRuleIndividual struct {
	// Prefix used on new room name
	RoomPrefix string `protobuf:"bytes,1,opt,name=room_prefix,json=roomPrefix,proto3" json:"room_prefix,omitempty"`
	// Optional pin required to enter room
	Pin                  string   `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIPDispatchRuleIndividual) Reset()         { *m = SIPDispatchRuleIndividual{} }
func (m *SIPDispatchRuleIndividual) String() string { return proto.CompactTextString(m) }
func (*SIPDispatchRuleIndividual) ProtoMessage()    {}
func (*SIPDispatchRuleIndividual) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{7}
}

func (m *SIPDispatchRuleIndividual) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIPDispatchRuleIndividual.Unmarshal(m, b)
}
func (m *SIPDispatchRuleIndividual) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIPDispatchRuleIndividual.Marshal(b, m, deterministic)
}
func (m *SIPDispatchRuleIndividual) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIPDispatchRuleIndividual.Merge(m, src)
}
func (m *SIPDispatchRuleIndividual) XXX_Size() int {
	return xxx_messageInfo_SIPDispatchRuleIndividual.Size(m)
}
func (m *SIPDispatchRuleIndividual) XXX_DiscardUnknown() {
	xxx_messageInfo_SIPDispatchRuleIndividual.DiscardUnknown(m)
}

var xxx_messageInfo_SIPDispatchRuleIndividual proto.InternalMessageInfo

func (m *SIPDispatchRuleIndividual) GetRoomPrefix() string {
	if m != nil {
		return m.RoomPrefix
	}
	return ""
}

func (m *SIPDispatchRuleIndividual) GetPin() string {
	if m != nil {
		return m.Pin
	}
	return ""
}

type CreateSIPDispatchRuleRequest struct {
	// Types that are valid to be assigned to Instrument:
	//	*CreateSIPDispatchRuleRequest_DispatchRuleDirect
	//	*CreateSIPDispatchRuleRequest_DispatchRulePin
	//	*CreateSIPDispatchRuleRequest_DispatchRuleIndividual
	Instrument isCreateSIPDispatchRuleRequest_Instrument `protobuf_oneof:"instrument"`
	// What trunks are accepted for this dispatch rule
	// If empty all trunks will match this dispatch rule
	TrunkIds []string `protobuf:"bytes,4,rep,name=trunk_ids,json=trunkIds,proto3" json:"trunk_ids,omitempty"`
	// By default the From value (Phone number) is used as the participant identity
	// If true a random value will be used instead
	HidePhoneNumber      bool     `protobuf:"varint,6,opt,name=hide_phone_number,json=hidePhoneNumber,proto3" json:"hide_phone_number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSIPDispatchRuleRequest) Reset()         { *m = CreateSIPDispatchRuleRequest{} }
func (m *CreateSIPDispatchRuleRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSIPDispatchRuleRequest) ProtoMessage()    {}
func (*CreateSIPDispatchRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{8}
}

func (m *CreateSIPDispatchRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSIPDispatchRuleRequest.Unmarshal(m, b)
}
func (m *CreateSIPDispatchRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSIPDispatchRuleRequest.Marshal(b, m, deterministic)
}
func (m *CreateSIPDispatchRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSIPDispatchRuleRequest.Merge(m, src)
}
func (m *CreateSIPDispatchRuleRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSIPDispatchRuleRequest.Size(m)
}
func (m *CreateSIPDispatchRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSIPDispatchRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSIPDispatchRuleRequest proto.InternalMessageInfo

type isCreateSIPDispatchRuleRequest_Instrument interface {
	isCreateSIPDispatchRuleRequest_Instrument()
}

type CreateSIPDispatchRuleRequest_DispatchRuleDirect struct {
	DispatchRuleDirect *SIPDispatchRuleDirect `protobuf:"bytes,1,opt,name=dispatch_rule_direct,json=dispatchRuleDirect,proto3,oneof"`
}

type CreateSIPDispatchRuleRequest_DispatchRulePin struct {
	DispatchRulePin *SIPDispatchRulePin `protobuf:"bytes,2,opt,name=dispatch_rule_pin,json=dispatchRulePin,proto3,oneof"`
}

type CreateSIPDispatchRuleRequest_DispatchRuleIndividual struct {
	DispatchRuleIndividual *SIPDispatchRuleIndividual `protobuf:"bytes,3,opt,name=dispatch_rule_individual,json=dispatchRuleIndividual,proto3,oneof"`
}

func (*CreateSIPDispatchRuleRequest_DispatchRuleDirect) isCreateSIPDispatchRuleRequest_Instrument() {}

func (*CreateSIPDispatchRuleRequest_DispatchRulePin) isCreateSIPDispatchRuleRequest_Instrument() {}

func (*CreateSIPDispatchRuleRequest_DispatchRuleIndividual) isCreateSIPDispatchRuleRequest_Instrument() {
}

func (m *CreateSIPDispatchRuleRequest) GetInstrument() isCreateSIPDispatchRuleRequest_Instrument {
	if m != nil {
		return m.Instrument
	}
	return nil
}

func (m *CreateSIPDispatchRuleRequest) GetDispatchRuleDirect() *SIPDispatchRuleDirect {
	if x, ok := m.GetInstrument().(*CreateSIPDispatchRuleRequest_DispatchRuleDirect); ok {
		return x.DispatchRuleDirect
	}
	return nil
}

func (m *CreateSIPDispatchRuleRequest) GetDispatchRulePin() *SIPDispatchRulePin {
	if x, ok := m.GetInstrument().(*CreateSIPDispatchRuleRequest_DispatchRulePin); ok {
		return x.DispatchRulePin
	}
	return nil
}

func (m *CreateSIPDispatchRuleRequest) GetDispatchRuleIndividual() *SIPDispatchRuleIndividual {
	if x, ok := m.GetInstrument().(*CreateSIPDispatchRuleRequest_DispatchRuleIndividual); ok {
		return x.DispatchRuleIndividual
	}
	return nil
}

func (m *CreateSIPDispatchRuleRequest) GetTrunkIds() []string {
	if m != nil {
		return m.TrunkIds
	}
	return nil
}

func (m *CreateSIPDispatchRuleRequest) GetHidePhoneNumber() bool {
	if m != nil {
		return m.HidePhoneNumber
	}
	return false
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*CreateSIPDispatchRuleRequest) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*CreateSIPDispatchRuleRequest_DispatchRuleDirect)(nil),
		(*CreateSIPDispatchRuleRequest_DispatchRulePin)(nil),
		(*CreateSIPDispatchRuleRequest_DispatchRuleIndividual)(nil),
	}
}

type SIPDispatchRuleInfo struct {
	SipDispatchRuleId    string   `protobuf:"bytes,1,opt,name=sip_dispatch_rule_id,json=sipDispatchRuleId,proto3" json:"sip_dispatch_rule_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIPDispatchRuleInfo) Reset()         { *m = SIPDispatchRuleInfo{} }
func (m *SIPDispatchRuleInfo) String() string { return proto.CompactTextString(m) }
func (*SIPDispatchRuleInfo) ProtoMessage()    {}
func (*SIPDispatchRuleInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{9}
}

func (m *SIPDispatchRuleInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIPDispatchRuleInfo.Unmarshal(m, b)
}
func (m *SIPDispatchRuleInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIPDispatchRuleInfo.Marshal(b, m, deterministic)
}
func (m *SIPDispatchRuleInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIPDispatchRuleInfo.Merge(m, src)
}
func (m *SIPDispatchRuleInfo) XXX_Size() int {
	return xxx_messageInfo_SIPDispatchRuleInfo.Size(m)
}
func (m *SIPDispatchRuleInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SIPDispatchRuleInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SIPDispatchRuleInfo proto.InternalMessageInfo

func (m *SIPDispatchRuleInfo) GetSipDispatchRuleId() string {
	if m != nil {
		return m.SipDispatchRuleId
	}
	return ""
}

type ListSIPDispatchRuleRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSIPDispatchRuleRequest) Reset()         { *m = ListSIPDispatchRuleRequest{} }
func (m *ListSIPDispatchRuleRequest) String() string { return proto.CompactTextString(m) }
func (*ListSIPDispatchRuleRequest) ProtoMessage()    {}
func (*ListSIPDispatchRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{10}
}

func (m *ListSIPDispatchRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSIPDispatchRuleRequest.Unmarshal(m, b)
}
func (m *ListSIPDispatchRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSIPDispatchRuleRequest.Marshal(b, m, deterministic)
}
func (m *ListSIPDispatchRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSIPDispatchRuleRequest.Merge(m, src)
}
func (m *ListSIPDispatchRuleRequest) XXX_Size() int {
	return xxx_messageInfo_ListSIPDispatchRuleRequest.Size(m)
}
func (m *ListSIPDispatchRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSIPDispatchRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSIPDispatchRuleRequest proto.InternalMessageInfo

type ListSIPDispatchRuleResponse struct {
	Items                []*SIPDispatchRuleInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *ListSIPDispatchRuleResponse) Reset()         { *m = ListSIPDispatchRuleResponse{} }
func (m *ListSIPDispatchRuleResponse) String() string { return proto.CompactTextString(m) }
func (*ListSIPDispatchRuleResponse) ProtoMessage()    {}
func (*ListSIPDispatchRuleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{11}
}

func (m *ListSIPDispatchRuleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSIPDispatchRuleResponse.Unmarshal(m, b)
}
func (m *ListSIPDispatchRuleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSIPDispatchRuleResponse.Marshal(b, m, deterministic)
}
func (m *ListSIPDispatchRuleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSIPDispatchRuleResponse.Merge(m, src)
}
func (m *ListSIPDispatchRuleResponse) XXX_Size() int {
	return xxx_messageInfo_ListSIPDispatchRuleResponse.Size(m)
}
func (m *ListSIPDispatchRuleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSIPDispatchRuleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSIPDispatchRuleResponse proto.InternalMessageInfo

func (m *ListSIPDispatchRuleResponse) GetItems() []*SIPDispatchRuleInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteSIPDispatchRuleRequest struct {
	SipDispatchRuleId    string   `protobuf:"bytes,1,opt,name=sip_dispatch_rule_id,json=sipDispatchRuleId,proto3" json:"sip_dispatch_rule_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSIPDispatchRuleRequest) Reset()         { *m = DeleteSIPDispatchRuleRequest{} }
func (m *DeleteSIPDispatchRuleRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSIPDispatchRuleRequest) ProtoMessage()    {}
func (*DeleteSIPDispatchRuleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{12}
}

func (m *DeleteSIPDispatchRuleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSIPDispatchRuleRequest.Unmarshal(m, b)
}
func (m *DeleteSIPDispatchRuleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSIPDispatchRuleRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSIPDispatchRuleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSIPDispatchRuleRequest.Merge(m, src)
}
func (m *DeleteSIPDispatchRuleRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSIPDispatchRuleRequest.Size(m)
}
func (m *DeleteSIPDispatchRuleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSIPDispatchRuleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSIPDispatchRuleRequest proto.InternalMessageInfo

func (m *DeleteSIPDispatchRuleRequest) GetSipDispatchRuleId() string {
	if m != nil {
		return m.SipDispatchRuleId
	}
	return ""
}

// A SIP Participant is a singular SIP session connected to a LiveKit room via
// a SIP Trunk into a SIP DispatchRule
type CreateSIPParticipantRequest struct {
	// What LiveKit room should this participant be connected too
	RoomName string `protobuf:"bytes,1,opt,name=room_name,json=roomName,proto3" json:"room_name,omitempty"`
	// What SIP Trunk should be used to dial the user
	SipTrunkId           string   `protobuf:"bytes,2,opt,name=sip_trunk_id,json=sipTrunkId,proto3" json:"sip_trunk_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateSIPParticipantRequest) Reset()         { *m = CreateSIPParticipantRequest{} }
func (m *CreateSIPParticipantRequest) String() string { return proto.CompactTextString(m) }
func (*CreateSIPParticipantRequest) ProtoMessage()    {}
func (*CreateSIPParticipantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{13}
}

func (m *CreateSIPParticipantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateSIPParticipantRequest.Unmarshal(m, b)
}
func (m *CreateSIPParticipantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateSIPParticipantRequest.Marshal(b, m, deterministic)
}
func (m *CreateSIPParticipantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateSIPParticipantRequest.Merge(m, src)
}
func (m *CreateSIPParticipantRequest) XXX_Size() int {
	return xxx_messageInfo_CreateSIPParticipantRequest.Size(m)
}
func (m *CreateSIPParticipantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateSIPParticipantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateSIPParticipantRequest proto.InternalMessageInfo

func (m *CreateSIPParticipantRequest) GetRoomName() string {
	if m != nil {
		return m.RoomName
	}
	return ""
}

func (m *CreateSIPParticipantRequest) GetSipTrunkId() string {
	if m != nil {
		return m.SipTrunkId
	}
	return ""
}

type SIPParticipantInfo struct {
	SipParticipantId     string   `protobuf:"bytes,1,opt,name=sip_participant_id,json=sipParticipantId,proto3" json:"sip_participant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIPParticipantInfo) Reset()         { *m = SIPParticipantInfo{} }
func (m *SIPParticipantInfo) String() string { return proto.CompactTextString(m) }
func (*SIPParticipantInfo) ProtoMessage()    {}
func (*SIPParticipantInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{14}
}

func (m *SIPParticipantInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIPParticipantInfo.Unmarshal(m, b)
}
func (m *SIPParticipantInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIPParticipantInfo.Marshal(b, m, deterministic)
}
func (m *SIPParticipantInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIPParticipantInfo.Merge(m, src)
}
func (m *SIPParticipantInfo) XXX_Size() int {
	return xxx_messageInfo_SIPParticipantInfo.Size(m)
}
func (m *SIPParticipantInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SIPParticipantInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SIPParticipantInfo proto.InternalMessageInfo

func (m *SIPParticipantInfo) GetSipParticipantId() string {
	if m != nil {
		return m.SipParticipantId
	}
	return ""
}

// DTMF Request lets you send a DTMF message for a SIP Participant
type SendSIPParticipantDTMFRequest struct {
	// What SIP Participant to send this DTMF for
	SipParticipantId string `protobuf:"bytes,1,opt,name=sip_participant_id,json=sipParticipantId,proto3" json:"sip_participant_id,omitempty"`
	// Digits that will be sent via DTMF
	Digits               string   `protobuf:"bytes,2,opt,name=digits,proto3" json:"digits,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendSIPParticipantDTMFRequest) Reset()         { *m = SendSIPParticipantDTMFRequest{} }
func (m *SendSIPParticipantDTMFRequest) String() string { return proto.CompactTextString(m) }
func (*SendSIPParticipantDTMFRequest) ProtoMessage()    {}
func (*SendSIPParticipantDTMFRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{15}
}

func (m *SendSIPParticipantDTMFRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendSIPParticipantDTMFRequest.Unmarshal(m, b)
}
func (m *SendSIPParticipantDTMFRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendSIPParticipantDTMFRequest.Marshal(b, m, deterministic)
}
func (m *SendSIPParticipantDTMFRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendSIPParticipantDTMFRequest.Merge(m, src)
}
func (m *SendSIPParticipantDTMFRequest) XXX_Size() int {
	return xxx_messageInfo_SendSIPParticipantDTMFRequest.Size(m)
}
func (m *SendSIPParticipantDTMFRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SendSIPParticipantDTMFRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SendSIPParticipantDTMFRequest proto.InternalMessageInfo

func (m *SendSIPParticipantDTMFRequest) GetSipParticipantId() string {
	if m != nil {
		return m.SipParticipantId
	}
	return ""
}

func (m *SendSIPParticipantDTMFRequest) GetDigits() string {
	if m != nil {
		return m.Digits
	}
	return ""
}

type SIPParticipantDTMFInfo struct {
	SipParticipantId     string   `protobuf:"bytes,1,opt,name=sip_participant_id,json=sipParticipantId,proto3" json:"sip_participant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SIPParticipantDTMFInfo) Reset()         { *m = SIPParticipantDTMFInfo{} }
func (m *SIPParticipantDTMFInfo) String() string { return proto.CompactTextString(m) }
func (*SIPParticipantDTMFInfo) ProtoMessage()    {}
func (*SIPParticipantDTMFInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{16}
}

func (m *SIPParticipantDTMFInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SIPParticipantDTMFInfo.Unmarshal(m, b)
}
func (m *SIPParticipantDTMFInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SIPParticipantDTMFInfo.Marshal(b, m, deterministic)
}
func (m *SIPParticipantDTMFInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SIPParticipantDTMFInfo.Merge(m, src)
}
func (m *SIPParticipantDTMFInfo) XXX_Size() int {
	return xxx_messageInfo_SIPParticipantDTMFInfo.Size(m)
}
func (m *SIPParticipantDTMFInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SIPParticipantDTMFInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SIPParticipantDTMFInfo proto.InternalMessageInfo

func (m *SIPParticipantDTMFInfo) GetSipParticipantId() string {
	if m != nil {
		return m.SipParticipantId
	}
	return ""
}

type ListSIPParticipantRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListSIPParticipantRequest) Reset()         { *m = ListSIPParticipantRequest{} }
func (m *ListSIPParticipantRequest) String() string { return proto.CompactTextString(m) }
func (*ListSIPParticipantRequest) ProtoMessage()    {}
func (*ListSIPParticipantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{17}
}

func (m *ListSIPParticipantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSIPParticipantRequest.Unmarshal(m, b)
}
func (m *ListSIPParticipantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSIPParticipantRequest.Marshal(b, m, deterministic)
}
func (m *ListSIPParticipantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSIPParticipantRequest.Merge(m, src)
}
func (m *ListSIPParticipantRequest) XXX_Size() int {
	return xxx_messageInfo_ListSIPParticipantRequest.Size(m)
}
func (m *ListSIPParticipantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSIPParticipantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListSIPParticipantRequest proto.InternalMessageInfo

type ListSIPParticipantResponse struct {
	Items                []*SIPParticipantInfo `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListSIPParticipantResponse) Reset()         { *m = ListSIPParticipantResponse{} }
func (m *ListSIPParticipantResponse) String() string { return proto.CompactTextString(m) }
func (*ListSIPParticipantResponse) ProtoMessage()    {}
func (*ListSIPParticipantResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{18}
}

func (m *ListSIPParticipantResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListSIPParticipantResponse.Unmarshal(m, b)
}
func (m *ListSIPParticipantResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListSIPParticipantResponse.Marshal(b, m, deterministic)
}
func (m *ListSIPParticipantResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListSIPParticipantResponse.Merge(m, src)
}
func (m *ListSIPParticipantResponse) XXX_Size() int {
	return xxx_messageInfo_ListSIPParticipantResponse.Size(m)
}
func (m *ListSIPParticipantResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListSIPParticipantResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListSIPParticipantResponse proto.InternalMessageInfo

func (m *ListSIPParticipantResponse) GetItems() []*SIPParticipantInfo {
	if m != nil {
		return m.Items
	}
	return nil
}

type DeleteSIPParticipantRequest struct {
	SipParticipantId     string   `protobuf:"bytes,1,opt,name=sip_participant_id,json=sipParticipantId,proto3" json:"sip_participant_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteSIPParticipantRequest) Reset()         { *m = DeleteSIPParticipantRequest{} }
func (m *DeleteSIPParticipantRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteSIPParticipantRequest) ProtoMessage()    {}
func (*DeleteSIPParticipantRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ae5cb80a6c08dd, []int{19}
}

func (m *DeleteSIPParticipantRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteSIPParticipantRequest.Unmarshal(m, b)
}
func (m *DeleteSIPParticipantRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteSIPParticipantRequest.Marshal(b, m, deterministic)
}
func (m *DeleteSIPParticipantRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteSIPParticipantRequest.Merge(m, src)
}
func (m *DeleteSIPParticipantRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteSIPParticipantRequest.Size(m)
}
func (m *DeleteSIPParticipantRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteSIPParticipantRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteSIPParticipantRequest proto.InternalMessageInfo

func (m *DeleteSIPParticipantRequest) GetSipParticipantId() string {
	if m != nil {
		return m.SipParticipantId
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateSIPTrunkRequest)(nil), "tc.CreateSIPTrunkRequest")
	proto.RegisterType((*SIPTrunkInfo)(nil), "tc.SIPTrunkInfo")
	proto.RegisterType((*ListSIPTrunkRequest)(nil), "tc.ListSIPTrunkRequest")
	proto.RegisterType((*ListSIPTrunkResponse)(nil), "tc.ListSIPTrunkResponse")
	proto.RegisterType((*DeleteSIPTrunkRequest)(nil), "tc.DeleteSIPTrunkRequest")
	proto.RegisterType((*SIPDispatchRuleDirect)(nil), "tc.SIPDispatchRuleDirect")
	proto.RegisterType((*SIPDispatchRulePin)(nil), "tc.SIPDispatchRulePin")
	proto.RegisterType((*SIPDispatchRuleIndividual)(nil), "tc.SIPDispatchRuleIndividual")
	proto.RegisterType((*CreateSIPDispatchRuleRequest)(nil), "tc.CreateSIPDispatchRuleRequest")
	proto.RegisterType((*SIPDispatchRuleInfo)(nil), "tc.SIPDispatchRuleInfo")
	proto.RegisterType((*ListSIPDispatchRuleRequest)(nil), "tc.ListSIPDispatchRuleRequest")
	proto.RegisterType((*ListSIPDispatchRuleResponse)(nil), "tc.ListSIPDispatchRuleResponse")
	proto.RegisterType((*DeleteSIPDispatchRuleRequest)(nil), "tc.DeleteSIPDispatchRuleRequest")
	proto.RegisterType((*CreateSIPParticipantRequest)(nil), "tc.CreateSIPParticipantRequest")
	proto.RegisterType((*SIPParticipantInfo)(nil), "tc.SIPParticipantInfo")
	proto.RegisterType((*SendSIPParticipantDTMFRequest)(nil), "tc.SendSIPParticipantDTMFRequest")
	proto.RegisterType((*SIPParticipantDTMFInfo)(nil), "tc.SIPParticipantDTMFInfo")
	proto.RegisterType((*ListSIPParticipantRequest)(nil), "tc.ListSIPParticipantRequest")
	proto.RegisterType((*ListSIPParticipantResponse)(nil), "tc.ListSIPParticipantResponse")
	proto.RegisterType((*DeleteSIPParticipantRequest)(nil), "tc.DeleteSIPParticipantRequest")
}

func init() { proto.RegisterFile("tc_sip.proto", fileDescriptor_37ae5cb80a6c08dd) }

var fileDescriptor_37ae5cb80a6c08dd = []byte{
	// 830 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0xed, 0x6e, 0xe2, 0x46,
	0x14, 0x0d, 0xd0, 0xa2, 0x70, 0x41, 0xd9, 0x64, 0x16, 0xa8, 0x63, 0xc8, 0x86, 0x75, 0xa5, 0x2a,
	0xaa, 0xb6, 0x50, 0xd1, 0x5f, 0x95, 0xba, 0x95, 0x9a, 0x45, 0x28, 0xb4, 0xf9, 0xb0, 0x4c, 0xd4,
	0xaa, 0x55, 0x25, 0xcb, 0xf1, 0x4c, 0xc2, 0xa8, 0x66, 0xec, 0x7a, 0xc6, 0x69, 0xfe, 0xf7, 0x1d,
	0xfa, 0x86, 0x7d, 0x8f, 0xca, 0x83, 0x6d, 0x6c, 0x3c, 0x50, 0xb1, 0xff, 0xc2, 0xbd, 0x9e, 0x33,
	0xe7, 0x1e, 0x9f, 0xe3, 0x1b, 0x68, 0x09, 0xd7, 0xe6, 0x34, 0x18, 0x06, 0xa1, 0x2f, 0x7c, 0x54,
	0x15, 0xae, 0xf1, 0x77, 0x05, 0x3a, 0x1f, 0x42, 0xe2, 0x08, 0x32, 0x9f, 0x99, 0xf7, 0x61, 0xc4,
	0xfe, 0xb0, 0xc8, 0x9f, 0x11, 0xe1, 0x02, 0xf5, 0xa1, 0xe1, 0x60, 0x1c, 0x12, 0xce, 0x09, 0xd7,
	0x2a, 0x83, 0xda, 0x45, 0xc3, 0x5a, 0x17, 0xd0, 0x11, 0x54, 0x85, 0xaf, 0x55, 0x07, 0x95, 0x8b,
	0x86, 0x55, 0x15, 0x3e, 0xfa, 0x0e, 0x74, 0xc7, 0xf3, 0xfc, 0xbf, 0x08, 0xb6, 0x31, 0xe1, 0x82,
	0x32, 0x47, 0x50, 0x9f, 0x71, 0x3b, 0x24, 0x4f, 0xe4, 0x45, 0xab, 0xc9, 0xe3, 0x5a, 0xf2, 0xc4,
	0x24, 0xf7, 0x80, 0x15, 0xf7, 0x8d, 0xaf, 0xa1, 0x95, 0x5e, 0x3f, 0x63, 0x8f, 0x3e, 0x1a, 0x40,
	0x8b, 0xd3, 0xc0, 0x16, 0x71, 0xc1, 0xa6, 0x58, 0xab, 0xc8, 0x7b, 0x80, 0xd3, 0x60, 0xf5, 0x0c,
	0x36, 0x3a, 0xf0, 0xfa, 0x9a, 0x72, 0xb1, 0x41, 0xda, 0xf8, 0x1e, 0xda, 0xc5, 0x32, 0x0f, 0x7c,
	0xc6, 0x09, 0xfa, 0x02, 0x3e, 0xa5, 0x82, 0x2c, 0x57, 0x83, 0x34, 0xc7, 0xc7, 0x43, 0xe1, 0x0e,
	0xf3, 0x37, 0x5a, 0xab, 0xb6, 0xf1, 0x2d, 0x74, 0x26, 0xc4, 0x23, 0x65, 0x35, 0xfe, 0x9f, 0xd1,
	0x14, 0x3a, 0xf3, 0x99, 0x39, 0xa1, 0x3c, 0x70, 0x84, 0xbb, 0xb0, 0x22, 0x8f, 0x4c, 0x68, 0x48,
	0x5c, 0x81, 0x7a, 0xd0, 0x08, 0x7d, 0x7f, 0x69, 0x33, 0x67, 0x49, 0x92, 0x73, 0x87, 0x71, 0xe1,
	0xd6, 0x59, 0x12, 0x74, 0x0c, 0xb5, 0x80, 0xb2, 0x44, 0xc8, 0xf8, 0x4f, 0xe3, 0x03, 0xa0, 0x0d,
	0x1c, 0x93, 0xb2, 0x7d, 0x41, 0x6e, 0xe1, 0x74, 0x03, 0x64, 0xc6, 0x30, 0x7d, 0xa6, 0x38, 0x72,
	0x3c, 0x74, 0x0e, 0x4d, 0x89, 0x15, 0x84, 0xe4, 0x91, 0xbe, 0xa4, 0xa3, 0xc4, 0x25, 0x53, 0x56,
	0x14, 0x78, 0xff, 0x56, 0xa1, 0x9f, 0xd9, 0x24, 0x0f, 0x9b, 0xea, 0x73, 0x03, 0x6d, 0x9c, 0x94,
	0xed, 0x30, 0xf2, 0x88, 0x8d, 0xe5, 0xf0, 0x12, 0xbc, 0x39, 0x3e, 0x4d, 0xf4, 0x2e, 0xab, 0x73,
	0x75, 0x60, 0x21, 0x5c, 0xd6, 0x6c, 0x02, 0x27, 0x45, 0xb8, 0x94, 0x4f, 0x73, 0xdc, 0x55, 0x60,
	0x99, 0x94, 0x5d, 0x1d, 0x58, 0xaf, 0xf0, 0x86, 0x68, 0xbf, 0x82, 0x56, 0x44, 0xa1, 0x99, 0x08,
	0x5a, 0x4d, 0x82, 0x9d, 0x29, 0xc0, 0xd6, 0x4a, 0x5d, 0x1d, 0x58, 0x5d, 0xac, 0xd6, 0xb0, 0x07,
	0x8d, 0xd4, 0x0b, 0x5c, 0xfb, 0x44, 0xda, 0xfb, 0x50, 0xac, 0x9c, 0xc0, 0xd1, 0x97, 0x70, 0xb2,
	0xa0, 0x98, 0xd8, 0xc1, 0xc2, 0x67, 0xc4, 0x66, 0xd1, 0xf2, 0x81, 0x84, 0x5a, 0x7d, 0x50, 0xb9,
	0x38, 0xb4, 0x5e, 0xc5, 0x0d, 0x33, 0xae, 0xdf, 0xca, 0xf2, 0x65, 0x0b, 0x80, 0x32, 0x2e, 0xc2,
	0x68, 0x49, 0x98, 0x30, 0xa6, 0xf0, 0xba, 0xc4, 0xe6, 0xd1, 0x47, 0x23, 0x68, 0xc7, 0xee, 0xdb,
	0x18, 0x26, 0x75, 0xe1, 0x09, 0xa7, 0x41, 0xe1, 0x08, 0x36, 0xfa, 0xa0, 0x27, 0x39, 0x50, 0xbc,
	0x2c, 0xe3, 0x1a, 0x7a, 0xca, 0x6e, 0x12, 0x96, 0xaf, 0x8a, 0x61, 0xf9, 0x4c, 0xa9, 0xd1, 0x3a,
	0x33, 0x77, 0xd0, 0xcf, 0x32, 0xa3, 0xb2, 0xc6, 0xde, 0xe4, 0x7f, 0x87, 0x5e, 0xe6, 0x35, 0xd3,
	0x09, 0x05, 0x75, 0x69, 0xe0, 0x30, 0x91, 0xe2, 0xed, 0x8c, 0xc2, 0x66, 0x4e, 0xab, 0xa5, 0x9c,
	0x5e, 0xca, 0x7c, 0xe5, 0x70, 0xa5, 0xc2, 0xef, 0x00, 0xc5, 0xe7, 0x82, 0x75, 0x79, 0x4d, 0xf1,
	0x98, 0xd3, 0x20, 0xff, 0x3c, 0x36, 0x08, 0x9c, 0xcd, 0x09, 0xc3, 0x45, 0x9c, 0xc9, 0xfd, 0xcd,
	0x34, 0xe5, 0xb8, 0x17, 0x1c, 0xea, 0x42, 0x1d, 0xd3, 0x27, 0x2a, 0x78, 0x42, 0x37, 0xf9, 0x65,
	0x4c, 0xa1, 0x5b, 0xbe, 0xe2, 0x23, 0xe8, 0xf6, 0xe0, 0x34, 0x79, 0xdf, 0x65, 0x39, 0x8d, 0x1f,
	0x33, 0xab, 0x14, 0x9a, 0x89, 0x17, 0xde, 0x15, 0xbd, 0x90, 0x86, 0x6f, 0x43, 0xbe, 0xd4, 0x0a,
	0x3f, 0x41, 0x2f, 0xb3, 0x82, 0xe2, 0xcd, 0xed, 0xc5, 0x7a, 0xfc, 0x4f, 0x1d, 0x6a, 0xf3, 0x99,
	0x89, 0xde, 0xc3, 0x51, 0x71, 0x43, 0x21, 0xf9, 0x39, 0x51, 0x6e, 0x2d, 0xbd, 0xf4, 0x65, 0x47,
	0x3f, 0x40, 0x2b, 0xbf, 0x12, 0x90, 0xb4, 0xb3, 0x62, 0x77, 0xe8, 0x5a, 0xb9, 0x91, 0x88, 0xf0,
	0x1e, 0x8e, 0x8a, 0x5b, 0x61, 0xc5, 0x40, 0xb9, 0x29, 0x14, 0x0c, 0xac, 0xdc, 0x8a, 0xcd, 0x5b,
	0x1d, 0x0d, 0x0a, 0x73, 0x28, 0xb2, 0xa3, 0x6f, 0xcb, 0x1e, 0xfa, 0x39, 0xdb, 0x7f, 0x05, 0xc4,
	0x37, 0xb9, 0x19, 0x54, 0x78, 0xe7, 0x5b, 0xfb, 0xc9, 0xa8, 0x56, 0x6e, 0x01, 0x96, 0xb9, 0xee,
	0xca, 0xf9, 0x76, 0xae, 0x77, 0xd0, 0x56, 0xe5, 0x19, 0x9d, 0x17, 0xc6, 0x2f, 0xfb, 0x45, 0xdf,
	0xe2, 0x36, 0xf4, 0x0b, 0x74, 0xd5, 0xf1, 0x43, 0x6f, 0xe5, 0x89, 0x5d, 0xd1, 0xd4, 0xf5, 0x32,
	0x68, 0x16, 0xab, 0x39, 0xa0, 0x72, 0x16, 0xd0, 0x59, 0x4e, 0x34, 0x05, 0xcb, 0x37, 0xdb, 0xda,
	0x89, 0xa4, 0x77, 0xd0, 0x56, 0x85, 0x62, 0x35, 0xfe, 0x8e, 0xb8, 0x6c, 0x1b, 0xff, 0xf2, 0xf3,
	0xdf, 0xde, 0x3e, 0x51, 0xb1, 0x88, 0x1e, 0x86, 0xae, 0xbf, 0x1c, 0x79, 0x34, 0x5a, 0x38, 0xd4,
	0xf3, 0x9f, 0xc9, 0x48, 0xfe, 0x5b, 0xe7, 0xfa, 0xde, 0x48, 0xb8, 0x0f, 0x75, 0xf9, 0xe3, 0x9b,
	0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0xc4, 0x4c, 0x5d, 0x9b, 0xf3, 0x09, 0x00, 0x00,
}
