package rtcconfig

const (
	// 缓冲的数据包数量
	readBufferSize = 50

	minUDPBufferSize       = 5_000_000
	writeBufferSizeInBytes = 4 * 1024 * 1024
	defaultUDPBufferSize   = 16_777_216
)

var DefaultStunServers = []string{
	"stun.l.google.com:19302",
	"stun1.l.google.com:19302",
}

// RTCConfig RTC配置
type RTCConfig struct {
	UDPPort                 uint32           `yaml:"udp_port,omitempty"`
	TCPPort                 uint32           `yaml:"tcp_port,omitempty"`
	ICEPortRangeStart       uint32           `yaml:"port_range_start,omitempty"`
	ICEPortRangeEnd         uint32           `yaml:"port_range_end,omitempty"`
	NodeIP                  string           `yaml:"node_ip,omitempty"`
	NodeIPAutoGenerated     bool             `yaml:"-"`
	STUNServers             []string         `yaml:"stun_servers,omitempty"`
	UseExternalIP           bool             `yaml:"use_external_ip"`
	UseICELite              bool             `yaml:"use_ice_lite,omitempty"`
	Interfaces              InterfacesConfig `yaml:"interfaces,omitempty"`
	IPs                     IPsConfig        `yaml:"ips,omitempty"`
	EnableLoopbackCandidate bool             `yaml:"enable_loopback_candidate"`
	UseMDNS                 bool             `yaml:"use_mdns,omitempty"`
	// 当 UseExternalIP 为 true 时，只向客户端通告外部 IP
	ExternalIPOnly bool `yaml:"external_ip_only,omitempty"`

	// 为了测试，禁用 UDP
	ForceTCP bool `yaml:"force_tcp,omitempty"`
}

type InterfacesConfig struct {
	Includes []string `yaml:"includes,omitempty"`
	Excludes []string `yaml:"excludes,omitempty"`
}

type IPsConfig struct {
	Includes []string `yaml:"includes,omitempty"`
	Excludes []string `yaml:"excludes,omitempty"`
}

func (conf *RTCConfig) Validate(development bool) error {
	// 如果没有设置端口则设置默认值
	if conf.UDPPort == 0 && conf.ICEPortRangeStart == 0 {
		// 为了更容易在dev模式/docker下运行，默认为单端口
		if development {
			conf.UDPPort = 7882
		} else {
			conf.ICEPortRangeStart = 50000
			conf.ICEPortRangeEnd = 60000
		}
	}

	var err error
	if conf.NodeIP == "" {
		conf.NodeIP, err = conf.determineIP()
		if err != nil {
			return err
		}
		conf.NodeIPAutoGenerated = true
	}

	return nil
}
